### ISSUE TITLE
unable to build 

### ISSUE THREAD

**Issue by JokerHYC** [PonnamKarthik/FlutterToast#1]
=== BUILD TARGET fluttertoast OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/fluttertoast-umbrella.h"
            ^
    /Users/huangyicheng1/Downloads/flutter_app/ios/Pods/Target Support Files/fluttertoast/fluttertoast-umbrella.h:13:9: note: in file included from /Users/huangyicheng1/Downloads/flutter_app/ios/Pods/Target Support Files/fluttertoast/fluttertoast-umbrella.h:13:
    #import "FluttertoastPlugin.h"
            ^
    /Users/huangyicheng1/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.1/ios/Classes/FluttertoastPlugin.h:1:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'fluttertoast'

**Comment by asmh1989** [comment]
any update?

**Comment by asmh1989** [comment]
@PonnamKarthik  I found delete  `SwiftFluttertoastPlugin.swift`, ios build will be done.

so please update.

thanks

**Comment by PonnamKarthik** [comment]
plugin updated check version 2.0.2
