### ISSUE TITLE
Background color does not fill the whole Toast

### ISSUE THREAD

**Issue by escamoteur** [PonnamKarthik/FlutterToast#10]
Hi,

first thanks for this great component. I just added it using your example code and the result looks like

![image](https://user-images.githubusercontent.com/16635729/43018051-9d90d5d2-8c58-11e8-8731-dda639440ee9.png)

Is that intended?

Something else, why can't I set a duration for Android?

All the best
Thomas

**Comment by escamoteur** [comment]
Toastlength seems to change noting at least on Android is that correct?

**Comment by CaiJingLong** [comment]
I met same bug.

**Comment by CaiJingLong** [comment]
I fix the background color in PR #11

**Comment by PonnamKarthik** [comment]
Check new packager Version 2.0.7

**Comment by escamoteur** [comment]
Yep. works!
