### ISSUE TITLE
IOS 打开图库返回后，toast 失效问题

### ISSUE THREAD

**Issue by xiejibiao** [PonnamKarthik/FlutterToast#105]
IOS 选择打开图库，选择图片或直接取消后，返回APP内，toast 无法显示

**Comment by lhcdims** [comment]
I would like to translate the above stated issus in English:

After opening the photo gallery(using the image_picker), pick a photo or press cancel, then go back to the app, the toast message can no longer be displayed.

**Comment by yuezaixz** [comment]
same issues

**Comment by yuezaixz** [comment]
source code use 
``` [[UIApplication sharedApplication].windows lastObject] ```
to showToast. 
This problem is top window is image picker window after picking photo.

**Comment by xiaoshangWow** [comment]
UIView *sourceView =  [[UIApplication sharedApplication].delegate window];
if (!sourceView) sourceView = [[[UIApplication sharedApplication] windows] lastObject];
[sourceView makeToast:msg
                         duration:time
                         position:CSToastPositionTop
                            style:style
             ];
Can this change solve the problem?

**Comment by xiaobeiy** [comment]
the same issue

**Comment by hu1095878620** [comment]
same issues

**Comment by AgoniAlways** [comment]
same issues；  fluttertoast: ^3.1.0
