### ISSUE TITLE
Can not show toast on Android anymore...

### ISSUE THREAD

**Issue by jinfagang** [ponnamkarthik/FlutterToast#113]
As I tested lately, this lib can not show toast on android anymore, but iOS work ok.... With the newest flutter

**Comment by PonnamKarthik** [comment]
@jinfagang Can you please let me know the flutter version and its channel

**Comment by jinfagang** [comment]
For sure:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G71a, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

And my android version is android 7

**Comment by DMingOu** [comment]
I had met it before , caused by the Exception: MissingPlugin...
Finally I try to restart the project  and  it works.

**Comment by jinfagang** [comment]
@DMingOu  I can not seen any crash log, this plugin works perfect before, but broken when I upgrade my flutter. What do you mean restart project? It's cache problem?

**Comment by PonnamKarthik** [comment]
@jinfagang I have tried to replicate your problem but its working fine myside

try these steps

uninstall your apk from device

```
flutter clean
flutter run -v
```

**Comment by jinfagang** [comment]
@PonnamKarthik I think it's mainly because of flutter version, did u tested with flutter version of master? (I posted above in flutter doctor)

**Comment by PonnamKarthik** [comment]
@jinfagang I have tested it in beta version
