### ISSUE TITLE
Fluttertoast.cancel() not work

### ISSUE THREAD

**Issue by avkojwer1** [ponnamkarthik/FlutterToast#116]
i am using your example code to call the method Fluttertoast.cancel() , but it not work for both platform(android and iOS)

**Comment by KimKiHyuk** [comment]
me neither, cancel() method is not working on Android 8.0.

**Comment by luckycreationsindia** [comment]
Working for me in simulator for Android but not working in iOS

**Comment by nihalreddy33** [comment]
Same here, even I am facing the same issue on iOS

**Comment by Prashant12461246** [comment]
i am facing same problem

**Comment by KennC** [comment]
same problem, too
