### ISSUE TITLE
IOS keyboard occlusion

### ISSUE THREAD

**Issue by hu1095878620** [ponnamkarthik/FlutterToast#118]
When the keyboard pops up, Toast will be blocked by the keyboard.

**Comment by dspoonia7** [comment]
I am also facing the same issue.

**Comment by dspoonia7** [comment]
@PonnamKarthik this issue is still happening on the iOS device, tried with the latest version v3.1.3. Though its working fine for Android devices.

@hu1095878620 did you find any workaround for this? Thanks!

**Comment by vinnarasuvinnu** [comment]
This issue is still there. Provide some resolution

**Comment by Renatinaveen** [comment]
This issue is still there. Provide a solution.
