### ISSUE TITLE
Add default value in ReadMe

### ISSUE THREAD

**Issue by anticafe** [PonnamKarthik/FlutterToast#122]
Hi, could you please add the default value for each parameter in the below table (ReadMe)?

property | description
-- | --
msg | String (Not Null)(required)
toastLength | Toast.LENGTH_SHORT or Toast.LENGTH_LONG (optional)
gravity | ToastGravity.TOP (or) ToastGravity.CENTER (or) ToastGravity.BOTTOM
timeInSecForIos | int (only for ios)
bgcolor | Colors.red
textcolor | Colors.white
fontSize | 16.0 (float)

**Comment by PonnamKarthik** [comment]
Updated
