### ISSUE TITLE
can i set gravity to fixed value ?

### ISSUE THREAD

**Issue by cyany** [ponnamkarthik/FlutterToast#124]
just like android document says  toast.setGravity(Gravity.TOP or Gravity.LEFT, 0, 0)?

**Comment by rahuldange09** [comment]
Yes just make your your common function in a file and call it all time.
Like

toast(String message){
`Fluttertoast.showToast(
        msg: message,
        gravity: ToastGravity.TOP,
    );`
}

toast("Hey Flutter");
