### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by erperejildo** [PonnamKarthik/FlutterToast#133]
**This is not an issue**

I need to use something different to `SnackBarBehavior` because I must update its contain and `SetState` does nothing here because the snack bar is built once, when the button is clicked.

When I display it I'll show a countdown. Is this something I could archive using this package?

**Comment by PonnamKarthik** [comment]
No we cannot by plugin but you can hack it a bit by 

showing a toast in `Flutter.periodic`
