### ISSUE TITLE
FlutterToast Message

### ISSUE THREAD

**Issue by ujas3279** [PonnamKarthik/FlutterToast#135]
i got following error

 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter (25624): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

**Comment by cipriancirstea** [comment]
Restart the app. `flutter run`
