### ISSUE TITLE
Fluttertoast.cancel() can not work on ios

### ISSUE THREAD

**Issue by chuxia98** [ponnamkarthik/FlutterToast#137]
Fluttertoast.cancel() can not cancel  toast when i  call Fluttertoast.showToast() many times on ios

**Comment by mikecbone** [comment]
I'm also having this issue where `cancel()` doesn't appear to work when attempting to call `showToast()` several times. 

> [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version
    10.0.18363.720], locale en-GB)

> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.6)

> iPhone Xs - iOS 13.3
