### ISSUE TITLE
混合开发时不能用这个插件吗？

### ISSUE THREAD

**Issue by FantasyWind2016** [PonnamKarthik/FlutterToast#138]
> The plugin `fluttertoast` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

上面是VSCode的控制台输出。
flutter版本1.12.13+bugfix.5

**Comment by yyt231** [comment]
解决了吗

**Comment by FantasyWind2016** [comment]
> 解决了吗

运行没问题，反正我直接用了[手动捂脸]

**Comment by PonnamKarthik** [comment]
fixed in v5.0.1
