### ISSUE TITLE
Please add WEB support ASAP

### ISSUE THREAD

**Issue by ramioooz** [PonnamKarthik/FlutterToast#140]
Hello developers,

Flutter now support WEB, yes it is in the beta channel now, but soon will be added to the stable release.
you made a very nice package here, I believe it should also be available for the web.

I suggest you be the first to do it.
My regards,
Rami

**Comment by liudonghua123** [comment]
I suggest to add desktop support too.

**Comment by PonnamKarthik** [comment]
Added web support check v4.0.0
