### ISSUE TITLE
web: style is very different/wrong for the toast versus what I see in app

### ISSUE THREAD

**Issue by jdeltoft** [PonnamKarthik/FlutterToast#149]
Here is my code:

    Fluttertoast.showToast(
        msg: "Error: Check Proxy/Gateway",
        toastLength: Toast.LENGTH_LONG,
        gravity: ToastGravity.BOTTOM,
        backgroundColor: Colors.white,
        textColor: colorizedMenuColor,
        fontSize: 16.0);

And here is what I see in the web now with 4.0.0 version:

![image](https://user-images.githubusercontent.com/4506303/77941614-101df300-7280-11ea-8878-2cb1425e6eaf.png)

versus the app:

![image](https://user-images.githubusercontent.com/4506303/77941661-22982c80-7280-11ea-8be5-f91368bf461d.png)

**Comment by jdeltoft** [comment]
also, the alignment in the app is centered, but in the web it seems to default to the bottom right?  Let me try to add a center widget around it.

**Comment by newCodeRunner** [comment]
@jdeltoft, there are 2 other options webPosition and webBgColor to do this. have you tried these? mine works fine on Chrome.

**Comment by IanChenBJ** [comment]
![{127A6E31-D882-4EBC-806C-40D7FDB5F3F5}_20200513181212](https://user-images.githubusercontent.com/23445059/81800389-59cb5000-9545-11ea-86d2-4178cb50cef3.jpg)
just found another issue with web using, just like pic above,the width is not correct even when I set toast length as long like below.
![{93C687BC-4667-4170-9175-486295A367AB}_20200513181440](https://user-images.githubusercontent.com/23445059/81800603-a6169000-9545-11ea-8469-7d84cdf2d254.jpg)

**Comment by jdeltoft** [comment]
Just FYI, I moved over to "oktoast" plugin, and all good now.

**Comment by PonnamKarthik** [comment]
> Center

@jdeltoft this plugins interactive with native system components so we cannot mix widgets with thems 

thanks
