### ISSUE TITLE
Round border is disabled when setting background color

### ISSUE THREAD

**Issue by thanhbinh84** [PonnamKarthik/FlutterToast#156]
Android 7 emulator: 
Color toast 
![Screenshot_1587439545](https://user-images.githubusercontent.com/366768/79822108-9a0e3700-83ba-11ea-8143-3a991a68d037.png)
Default toast
![Screenshot_1587439609](https://user-images.githubusercontent.com/366768/79822117-a1354500-83ba-11ea-9a99-19130099d81d.png)

**Comment by emilioheinz** [comment]
Same here, any idea?

**Comment by antoniosap** [comment]
same

**Comment by emilioheinz** [comment]
Hey guys, I've moved to this lib https://github.com/OpenFlutter/flutter_oktoast. It is almost the same, but it is a way more customizable.

**Comment by PonnamKarthik** [comment]
@thanhbinh84  check with latest version, please check readme and changelog first

thanks
