### ISSUE TITLE
showToast should take a widget

### ISSUE THREAD

**Issue by karrarkazuya** [PonnamKarthik/FlutterToast#158]
Fluttertoast.showToast(...) should take a widget instead of raw text with msg as if what if i want to use a different font or use image or anything else than a text.  maybe an animated text even. the text only is very limited option

**Comment by gabrielintang** [comment]
this would be very helpful

**Comment by PonnamKarthik** [comment]
@gabrielintang @karrarkazuya its not possible with this library as it shows the toast from native platform

**Comment by gabrielintang** [comment]
I see @PonnamKarthik .. thanks for the explanation
