### ISSUE TITLE
The plugin calls the build of the previous widget

### ISSUE THREAD

**Issue by sostenesgomes** [PonnamKarthik/FlutterToast#16]
I have two stateful widgets.

When I navigate from first to second and in the second I call Fluttertoast.showToast, then the build method of the first widget is being called.

Flutter 0.5.1.
fluttertoast: ^2.0.7

**Comment by PonnamKarthik** [comment]
@sostenesgomes Please check with latest plugin v2.0.8

**Comment by PonnamKarthik** [comment]
closing as no response from user
