### ISSUE TITLE
I wish to control the time of Toast to appear on screen as per my needs

### ISSUE THREAD

**Issue by elaishane** [PonnamKarthik/FlutterToast#165]
I want Toast.LENGTH_LONG timing to increase by 3-7 seconds.
I want it as per my need

**Comment by RaashVision** [comment]
Issue still opened? We need flexibility to increase the time

**Comment by PonnamKarthik** [comment]
Android doesn't support time in seconds 

as this plugins uses Native Toast functionality this is not possible 

Thanks
