### ISSUE TITLE
background color not work

### ISSUE THREAD

**Issue by lukaskris** [PonnamKarthik/FlutterToast#168]
Background color not work from version 4.0.0 and 4.0.1
I've tested android only

**Comment by lukaskris** [comment]
It solved add `textColor: Colors.white,`

but not rounded background toast

**Comment by valtlfelipe** [comment]
Same here.

**Comment by Ghassan-Aljaafri** [comment]
same problem.

**Comment by Ghassan-Aljaafri** [comment]
> It solved add `textColor: Colors.white,`
> 
> but not rounded background toast

this is worked thank you, keep it up.
