### ISSUE TITLE
I can't set toast radius and textPadding

### ISSUE THREAD

**Issue by qinting513** [PonnamKarthik/FlutterToast#172]
I can't custom my toast,
for example: 
 Fluttertoast.showToast(
      msg:'hello'
      duration: Duration(seconds: duration),
      position: ToastPosition.bottom,
      backgroundColor: Colors.black.withOpacity(0.7),
      radius: 30.0,
      textPadding: EdgeInsets.fromLTRB(20, 14, 20, 14),
      textStyle: TextStyle(fontSize: 16.0, color: Colors.red),
     );
I think an ellipse is better looking than a rectangle.

**Comment by PonnamKarthik** [comment]
This plugin deals with Native Toasts Flutter widgets wont work
