### ISSUE TITLE
Flutter toast doesnt go well with admobs throws Unhandled Exception: error

### ISSUE THREAD

**Issue by Chethansmash7** [PonnamKarthik/FlutterToast#173]
When I implemented flutter toast for the first time it went well.But the next time after I implemented admob(firebase_admob) I dont know what happened I am getting the following error.Would anyone here please solve this problem??I need to update my version of my app.This is a very big error for me

E/flutter ( 4036): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter ( 4036): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 4036): <asynchronous suspension>
E/flutter ( 4036): #1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:68:31)
E/flutter ( 4036): #2      callback (package:flutterappstareawayv1/alertTime2.dart:19:16)
E/flutter ( 4036): #3      _alarmManagerCallbackDispatcher.<anonymous closure> (package:android_alarm_manager/android_alarm_manager.dart:43:14)
E/flutter ( 4036): #4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter ( 4036): #5      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter ( 4036): #6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter ( 4036): #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter ( 4036): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 4036): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4036): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 4036): #11     _invoke3 (dart:ui/hooks.dart:302:10)

**Comment by Chethansmash7** [comment]
Well I solved this problem.I had done something wrong with the implementation of the alarm manager configuration.Toast is working fine

**Comment by ayan7791** [comment]
@Chethansmash7 Can you please let me know the root cause? I am facing the same issue.
I haven't done any configuration for alarm manager.
