### ISSUE TITLE
PlatformException (error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)

### ISSUE THREAD

**Issue by lukaskris** [PonnamKarthik/FlutterToast#174]
I using version 4.0.1

its error when using background color, and text color. 
intermittent condition sometimes works fine and sometimes error like this.

`E/flutter (20711): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
E/flutter (20711): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (20711): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (20711): <asynchronous suspension>
E/flutter (20711): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (20711): #3      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:68:31)`

**Comment by PonnamKarthik** [comment]
@lukaskris check with latest version, please check readme and changelog first

thanks
