### ISSUE TITLE
FlutterToast not working anymore

### ISSUE THREAD

**Issue by ahmedzu** [PonnamKarthik/FlutterToast#176]
Performing hot restart...
Syncing files to device SM G570F...
Restarted application in 2,808ms.
D/ViewRootImpl@b776c11[MainActivity](17759): ViewPostIme pointer 0
D/ViewRootImpl@b776c11[MainActivity](17759): ViewPostIme pointer 1
D/InputTransport(17759): Input channel constructed: fd=104
D/ViewRootImpl@93cc3e2[Toast](17759): setView = android.widget.LinearLayout{55a7373 V.E...... ......I. 0,0-0,0} TM=true MM=false
V/Toast   (17759): Text: بلسل in android.widget.Toast$TN@4a26230
D/ViewRootImpl@93cc3e2[Toast](17759): dispatchAttachedToWindow
V/Surface (17759): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@93cc3e2[Toast](17759): Relayout returned: old=[0,0][0,0] new=[245,1092][475,1180] result=0x7 surface={valid=true 3245803520} changed=true
D/ViewRootImpl@93cc3e2[Toast](17759): MSG_RESIZED_REPORT: frame=Rect(245, 1092 - 475, 1180) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=١
D/ViewRootImpl@93cc3e2[Toast](17759): dispatchDetachedFromWindow
D/InputEventReceiver(17759): channel '83bf8d8 Toast (client)' ~ Disposing input event receiver.
D/InputEventReceiver(17759): channel '83bf8d8 Toast (client)' ~NativeInputEventReceiver.
D/InputTransport(17759): Input channel destroyed: fd=104

**Comment by PonnamKarthik** [comment]
@ahmedzu Check with latest version and let me know

Thanks
