### ISSUE TITLE
Failed assertion: line 132 pos 12: '_overlay != null': is not true

### ISSUE THREAD

**Issue by darrinps** [PonnamKarthik/FlutterToast#177]
Using version: toast: ^0.1.5
Flutter is up to date as of today
Code looks like this:

`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const fabPadding = EdgeInsets.all(5);

    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('State Notifier Demo'),
        ),
        floatingActionButton: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            Padding(
              padding: fabPadding,
              child: FloatingActionButton(
                child: Icon(Icons.add),

                ///Increment Counter
                onPressed: () {
                  //NOTE: Add this to access the increment method in the model
                  Toast.show("Toast 1", context, duration: Toast.LENGTH_SHORT, gravity: Toast.CENTER);
                  Toast.show("Toast 2", context, duration: Toast.LENGTH_SHORT, gravity: Toast.CENTER);
                  Toast.show("Toast 3", context, duration: Toast.LENGTH_SHORT, gravity: Toast.CENTER);
   ...
`

Here is the exception it throws:

E/flutter (19152): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 132 pos 12: '_overlay != null': is not true.
E/flutter (19152): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (19152): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (19152): #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:132:12)
E/flutter (19152): #3      ToastView.dismiss (package:toast/toast.dart:77:20)
E/flutter (19152): #4      Toast.show (package:toast/toast.dart:18:15)
E/flutter (19152): #5      MyApp.build.<anonymous closure> (package:flutterappstatenotifier/main.dart:54:25)
E/flutter (19152): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (19152): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (19152): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19152): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)

Flutter Doctor reports no issues.

Running this on an Android emulator.

**Comment by PonnamKarthik** [comment]
@darrinps issue is for this plugin [https://pub.dev/packages/toast](https://pub.dev/packages/toast) please reach to that dev

Thanks
