### ISSUE TITLE
Feature Request - Decoration option

### ISSUE THREAD

**Issue by royibernthal** [PonnamKarthik/FlutterToast#178]
Can you please add the option to add a decoration option?

For instance, I'd like my toast's corners to be completely round. (e.g. round rectangle with radius 40)

**Comment by PonnamKarthik** [comment]
Check latest readme

**Comment by royibernthal** [comment]
I did, can you help me see what I'm missing?

**Comment by PonnamKarthik** [comment]
I am pushing the new code today
