### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by pojoba02** [PonnamKarthik/FlutterToast#18]
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :fluttertoast.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

**Comment by yy1300326388** [comment]
I have encountered the same problem, change kotlin_version, please upgrade the author, release a new version, there will be problems in Android Studio 3.2.
@PonnamKarthik

**Comment by pojoba02** [comment]
Yea!!! is just a pain in the neck, l did update and upgrade in the build gradle but can't go beyond apk release,

**Comment by PonnamKarthik** [comment]
Thanks for reporting will resolve it today @pojoba02 and @yy1300326388

**Comment by PonnamKarthik** [comment]
@pojoba02 and @yy1300326388  please check new latest version of plugin v2.0.8

**Comment by savinmathew** [comment]
@PonnamKarthik v2.0.8 is failing too... 

> 

Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :fluttertoast.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

>

**Comment by pojoba02** [comment]
Is still throwing build failed with an exception, it does run well when debugging doe, it only failed when building the apk release

**Comment by yy1300326388** [comment]
kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead

**Comment by yy1300326388** [comment]
dependencies {
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Comment by yy1300326388** [comment]
fluttertoast-2.0.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.kt: (75, 32): 'setBackgroundDrawable(Drawable!): Unit' is deprecated. Deprecated in Java

**Comment by yy1300326388** [comment]
fluttertoast-2.0.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.kt: (80, 22): 'setBackgroundDrawable(Drawable!): Unit' is deprecated. Deprecated in Java

**Comment by yy1300326388** [comment]
I think it has a relationship with the kotlin upgrade, so please fix these obsolete apis. @PonnamKarthik

**Comment by pojoba02** [comment]
@PonnamKarthik, the example folder have a different android studio configuration,
the distributionUrl=4.1
targetSdkVersion=27
class path for android tools build gradle=3.0.1
ext.kotlin_version=1.1.51
can you please troubleshoot with the current configuration you have, cos am loosing sleep over this issue.
Current distributionUrl=4.6
targetSdkVersion=28
class path for android tool build gradle=3.2.0
current ext.kotlin_version=1.2.51

Thanks

**Comment by pojoba02** [comment]
@yy1300326388 and @savinmathew  where you guys able to figure it out the solution for it?

Thanks

**Comment by PonnamKarthik** [comment]
@pojoba02, @yy1300326388 and @savinmathew 

for temprory fix 

```gradle
lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
}
```

add this line in your project

location 'android/app/build.gradle'

**Comment by PonnamKarthik** [comment]
You can use class path for android tool build gradle=3.1.2
