### ISSUE TITLE
How to customize the display duration of toast for android

### ISSUE THREAD

**Issue by Chethansmash7** [PonnamKarthik/FlutterToast#182]
I am using flutter toast in my project .I want to show the toast for either 1 or 2 or 3 or 4 or 5 seconds.
But here I can see only for iOS there is the option
For android there seems to be only Toast length ,long or Short....

How to customize the display duration of toast

  Fluttertoast.showToast(
      msg:
          "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      toastLength: Toast.LENGTH_LONG,//how do you set this field to the time duration you want
      timeInSecForIos: 5,
      gravity: ,
      backgroundColor: ,
      textColor: ,
      fontSize: );
}

**Comment by PonnamKarthik** [comment]
Not Possible with android default toast
