### ISSUE TITLE
Toast invisable on android huawei honor devices

### ISSUE THREAD

**Issue by wei-spring** [PonnamKarthik/FlutterToast#184]
This is a bug for honor devices when show Toast not in main thread:
should fix:

Class:
`io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin#onMethodCall`

line 96:

```
if (mContext instanceof Activity) {
    ((Activity) mContext).runOnUiThread(new Runnable() {
        @Override
        public void run() {
            mToast.show();
        }
    });
} else {
    mToast.show();
}
```

**Comment by PonnamKarthik** [comment]
@wei-spring merged in latest release please check changelog and readme 

thanks
