### ISSUE TITLE
Problem starting on ios

### ISSUE THREAD

**Issue by rodrigorahman** [ponnamkarthik/FlutterToast#188]
I had a problem updating the package to version 5.0.1

this error happens only in ios

error log follows:
```

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Flutter
      - fluttertoast
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    [!] The name of the given podspec `FlutterToast` doesn't match the expected one `fluttertoast`
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/sandbox.rb:311:in `store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone 11 Pro Max.
```

Flutter doctor: 
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale pt-BR)
    • Flutter version 1.17.4 at
      /Users/rodrigorahman/Documents/workstation/bin/flutter
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rodrigorahman/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/rodrigorahman/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/rodrigorahman/Library/Android/sdk
    • Java binary at: /Users/rodrigorahman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 4.0)
    • Android Studio at /Users/rodrigorahman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E04CC9E7-9FFA-4CC5-92B4-BDAA0C32CC2D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 2 categories.

**Comment by umair2ooo** [comment]
Facing exactly same issue
it disturbed my whole project
I tried lots of different solutions
due to which I am not able to run the project even after removing this fluttertoast

**Comment by Shakle** [comment]
Same here.
[!] The name of the given podspec `FlutterToast` doesn't match the expected one `fluttertoast`

**Comment by tanuj-wagh** [comment]
Same here - The name of the given podspec FlutterToast doesn't match the expected one fluttertoast

**Comment by tanhx2008** [comment]
Same here.
[!] The name of the given podspec `FlutterToast` doesn't match the expected one `fluttertoast`

**Comment by SaxPlayer** [comment]
Same problem as others have mentioned. Falling over when trying to `flutter build ios`. Responds with:

`-> Fetching podspec for fluttertoast from .symlinks/plugins/fluttertoast/ios`
`[!] The name of the given podspec FlutterToast doesn't match the expected one fluttertoast`

I'm using FlutterToast version 5.0.1 in a project that previously used version 3.1.0. I've had to update other plugins as my app that has worked for a couple of years in Flutter and was last updated earlier this year is now no longer building on iOS, so I'm having to go through the painful task of updating plugins. It's enough to put you right off Flutter, although I've had similar issues with other cross platform dev systems. As I update each plugin, the next one has a problem, however this fail when building with FlutterToast is a complete show stopper. 

I ran `flutter pub cache repair` and have also run `flutter clean` prior to `flutter build ios`. Makes no difference.

Any help/advice very much appreciated!!!

**Comment by edsonboldrini** [comment]
My workaround for now was downgrade the version to 4.0.1 and it worked!

**Comment by xalikoutis** [comment]
same problem here after upgrading to 5.0.1

**Comment by martin-labanic** [comment]
Hit the same issue with version `5.0.1`.

> Facing exactly same issue
> it disturbed my whole project
> I tried lots of different solutions
> due to which I am not able to run the project even after removing this fluttertoast

Running the `flutter clean` command should remove any lingering code if you've already removed the plugin from your `pubspec.yaml` file.
