### ISSUE TITLE
New version is more complicated to use

### ISSUE THREAD

**Issue by allanwolski** [ponnamkarthik/FlutterToast#191]
The new version of the plugin is more complicated to use.
I would like to use the plugin to display a simple message from a class without context.

```
FlutterToast.showToast(
   msg: msg,
   fontSize: 14.0,
   backgroundColor: Colors.black26,
);
```

**Comment by klvnco** [comment]
agree new version is complicated and I'm getting a null error 
E/flutter ( 4141): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'showToast' was called on null.
E/flutter ( 4141): Receiver: null
E/flutter ( 4141): Tried calling: showToast(child: Instance of 'Container', gravity: Instance of 'ToastGravity', toastDuration: Instance of 'Duration')
E/flutter ( 4141): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4141): #1      _CustomFormWidget._showToast (package:tracker/src/customwidget/CustomFormWidget.dart:109:18)

**Comment by klvnco** [comment]
and how do we resolve the iOS side ? 
empty paragraph passed to @param
/**
 @param queueEnabled
 */
+ (void)setQueueEnabled:(BOOL)queueEnabled;

**Comment by dvnr76** [comment]
> agree new version is complicated and I'm getting a null error
> E/flutter ( 4141): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'showToast' was called on null.
> E/flutter ( 4141): Receiver: null
> E/flutter ( 4141): Tried calling: showToast(child: Instance of 'Container', gravity: Instance of 'ToastGravity', toastDuration: Instance of 'Duration')
> E/flutter ( 4141): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> E/flutter ( 4141): #1 _CustomFormWidget._showToast (package:tracker/src/customwidget/CustomFormWidget.dart:109:18)

**Comment by dvnr76** [comment]
I am also getting the same error

**Comment by ponnamkarthik** [comment]
Hello all,

New version requires the plugin needs to be initialized first

Then only we can be able to use 

After reading your comments I have decided to revert it to old version but also include the new one also 

I work on it and push the code asap

Thanks for your feedback

**Comment by bradintheusa** [comment]
Agreed the new version requires too much code.

**Comment by jhomlala** [comment]
Agree, we should be able to show toast without context.

**Comment by chanyunyu** [comment]
Agree, we should be able to show toast without context.

**Comment by ponnamkarthik** [comment]
Hello all,

As per many users feedback reverted back to old code but also mainted new code

you can access old code `Fluttertoast` and new code which requires context with `FToast`
