### ISSUE TITLE
Toast backgroundColor transparency not working

### ISSUE THREAD

**Issue by abianche** [ponnamkarthik/FlutterToast#197]
I can't get the background color to have some transparency.
e.g.: using
`backgroundColor: Colors.black12`
I expect to get a bg color with just 12% of opacity, however it's just full opaque.

Is there a way to add some transparency to the background color of the toast?

**Comment by Rammehar** [comment]
I have same problem of backgroundColor with opacity

**Comment by severance88** [comment]
I've also tried to do this the "normal" way without success. It always goes to the plugin default black.

I think what we need is here [Toast with buildcontext](https://github.com/ponnamkarthik/FlutterToast#toast-with-buildcontext).

We can give it our own child to render as the toast.
