### ISSUE TITLE
MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

### ISSUE THREAD

**Issue by Alok81234881** [ponnamkarthik/FlutterToast#198]
After adding flutter screen in my existing ios app, I am getting this following runtime error:

    '[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method 
    showToast on channel PonnamKarthik/fluttertoast)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>'
Any solution for this?

**Comment by ponnamkarthik** [comment]
@Alok81234881 Try restarting the application (full restart) 

or

try flutter clean then install

If error still persists please provide sample code 

Thanks

**Comment by Alok81234881** [comment]
Still getting the same error. Here is the sample code:
     'AppDelegate.swift

          import UIKit
          import Flutter
          import FlutterPluginRegistrant

        @UIApplicationMain
        class AppDelegate: FlutterAppDelegate  {

              lazy var flutterEngine = FlutterEngine(name: "my flutter engine")
             override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
              [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                  
                     flutterEngine.run();
                  
                     GeneratedPluginRegistrant.register(with: self.flutterEngine);
                   return super.application(application, didFinishLaunchingWithOptions: launchOptions);
         }
    }

ViewController.swift

       import UIKit
       import Flutter
       import FlutterPluginRegistrant

      class ViewController: UIViewController {

            override func viewDidLoad() {
              super.viewDidLoad()
             
            let flutterEngine = (UIApplication.shared.delegate as! AppDelegate).flutterEngine
            let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
           present(flutterViewController, animated: true, completion: nil)
       }


  Main.dart

      import 'package:flutter/material.dart';
      import 'package:flutter/services.dart';
      import 'package:fluttertoast/fluttertoast.dart';

     void main() => runApp(MyApp());

     class MyApp extends StatefulWidget {
          @override
          _MyAppState createState() => _MyAppState();
      }

      class _MyAppState extends State<MyApp> {

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                 home: Scaffold(
                  appBar: AppBar(
                      title: const Text('Razorpay Sample App'),
                   ),
                body: Center(
                       child: Row(
                             mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                             RaisedButton(onPressed: buttonClicked, child: Text('Show Toast'))
                             ])),
                         ),
                 );
           }
          void buttonClicked() async {
                   try {
                         Fluttertoast.showToast(msg: "Alok Singh: ", timeInSecForIos: 4);
                   } catch (e) {
                       debugPrint(e);
                      }
              }
        }



 Flutter Doctor

     [✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.17.3 at /Users/aloksingh/Developer/flutter
    • Framework revision b041144f83 (7 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/aloksingh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode 2.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

    [✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

    [✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 3D27866E-392A-454E-9406-214C0538A0EE • ios • 
       com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)

     • No issues found!

**Comment by amuchand47** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

Bro, I am getting the error?

**Comment by ponnamkarthik** [comment]
https://github.com/flutter/flutter/issues/23832

**Comment by surhidamatya** [comment]
Facing this issue.
Please the example code snippet
```
//Please note it is an async method
void updateUserProfile(
      String firstName, String lastName, String userName, String email) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    if (prefs.get(Constants.API_Token) == null ||
        prefs.get(Constants.API_Token) == '') {
      loginToast('Please Login to update profile!!!');
    } else {
      CommonHelper.showProgressBar(context, "Requesting ..........");
      updateProfile(firstName, lastName, userName, email).then((response) {
        if (response['status'] == true) {
          loginToast('Profile Updated');
          User user = response['data'];
          Prefs.setDisplayName(user.displayName);
          Prefs.setEmail(user.email);
          Prefs.setUserName(user.username);
          Prefs.setMobile(user.mobile);

          Navigator.of(context).pop();
        } else {
          loginToast(
              'Sorry could not Update Profile. Please try again later!!!');
        }
        FocusScope.of(context).unfocus();
        Navigator.of(context, rootNavigator: true).pop('dialog');
      });
    }
  }
```

The code I am using to show toast. This code is inside util class
 ```
//code snippet fomr util class
 void loginToast(String message) {
    Fluttertoast.showToast(
        msg: message,
        toastLength: Toast.LENGTH_LONG,
        gravity: ToastGravity.CENTER,
        backgroundColor: Colors.white,
        textColor: Colors.green,
        fontSize: 16.0);
  }
}
```

**Comment by muneebahmad0600** [comment]
facing the same issue. can it be because i am using null safe version with the flutter sdk version that is not null safe ?

**Comment by RathanVeer** [comment]
1- flutter clean
2- run
works for me!!

**Comment by MohammedFared** [comment]
I encountered this issue when running on the iOS platform and tried `flutter clean`, as recommended by others, but nothing worked for me except for deleting the `podfile.lock` and running `pod install`.

If you want a complete set of commands, copy/paste this into terminal:

```
cd ios
rm Podfile.lock
pod install
cd ..
flutter pub get
```
