### ISSUE TITLE
Toast is not shown on Android

### ISSUE THREAD

**Issue by SongHuaixu** [ponnamkarthik/FlutterToast#202]
version 7.0.1

Code: Fluttertoast.showToast(
        msg: text, gravity: ToastGravity.BOTTOM, timeInSecForIosWeb: 1);

Error:  D/EGL_emulation(23171): eglMakeCurrent: 0xddf1a240: ver 3 0 (tinfo 0xddf0f720)

**Comment by Cyua** [comment]
Same problems.

**Comment by DuskMount** [comment]
May be the bug of default backgroundColor and textColor.
Set parameter smanually may fix the problem:
      _backgroundColor: Colors.grey,
      textColor: Colors.white,_

**Comment by SongHuaixu** [comment]
Thank you. That's it
