### ISSUE TITLE
Web Fluttertoast.showToast  textColor not working

### ISSUE THREAD

**Issue by JustMyLive** [ponnamkarthik/FlutterToast#204]
For the flutter web App, I use Fluttertoast.showToast() function and set textColor to Colors.back. 
But It still show the white color for text.

Could you help me.

Flutter version:
Flutter (Channel beta, 1.20.0-7.3.pre, on Mac OS X 10.15.5 19F101, locale  zh-Hans-CN)

**Comment by djpeinado** [comment]
Fluttertoast uses [toastify-js](https://github.com/apvarun/toastify-js) in the web implementation.
It does not allow to set text color with a parameter, but you can set it right after toast is shown using css style.

```dart
import 'package:fluttertoast/fluttertoast.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:ui';
import 'dart:html' as html;

    Fluttertoast.showToast(msg: 'message');
    if (kIsWeb) {
      html.Element toast = html.querySelector('.toastify');
      toast.style.setProperty('color', '#000000'); // black
    }
```

**Comment by ponnamkarthik** [comment]
No `textcolor` will be set to the toast text color
