### ISSUE TITLE
UIPickerViewController show once, the toast never show again-----iOS

### ISSUE THREAD

**Issue by cbahai** [ponnamkarthik/FlutterToast#208]
如题

**Comment by cbahai** [comment]
https://www.jianshu.com/p/8c44251babed

**Comment by andersonmendesdev** [comment]
I have the same problem on ios, it is called a few times and then no longer responds.

**Comment by niceseee** [comment]
same issue on IOS.

**Comment by MrFanco** [comment]
when I `pod install`, it will install failed,can you give me some suggeston?

**Comment by cbahai** [comment]
[It's been fixed.](https://github.com/ponnamkarthik/FlutterToast/commit/1c9f50bbd6f682ea91a1ef093cdb248b63143241)
