### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by liuzhibopp** [ponnamkarthik/FlutterToast#211]
fluttertoast: ^7.0.2
Adding flutter to an Android app ,when build apk show error, by the way  v4.0.0 do
 not have this error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

**Comment by ponnamkarthik** [comment]
Please check latest version
