### ISSUE TITLE
UIView+Toast.o duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by hc2088** [ponnamkarthik/FlutterToast#212]
duplicate symbol '_OBJC_IVAR_$_CSToastManager._queueEnabled' in:
    /Users/xx/Desktop/commercial_frameworks/xx/libxxx.a(UIView+Toast.o)
    /Users/xx/Library/Developer/Xcode/DerivedData/xxx-dtmfbratpdgyklbqvnmbtbnwhaje/Build/Products/Debug-iphoneos/fluttertoast/libfluttertoast.a(UIView+Toast.o)
ld: 34 duplicate symbols for architecture arm64

@interface UIView (Toast)
UIView+Toast.h

能把这个类相关方法&变量重新重新命名一下吗

**Comment by liuxinghudiejie** [comment]
same problem

**Comment by jackkang0401** [comment]
UIView+Toast duplicate symbol

**Comment by liuxinghudiejie** [comment]
目前我的解决办法是：在xcode中搜索这两个文件，删除引用关系

**Comment by ponnamkarthik** [comment]
Hope #228 Fixed it published the `7.1.0`
