### ISSUE TITLE
The plugin fluttertoast could not be built due to the issue above.

### ISSUE THREAD

**Issue by patelronakp** [ponnamkarthik/FlutterToast#214]
e: C:\XXX\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-7.0.2\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (4, 28): Unresolved reference: Non
Null

Plugin Version 
fluttertoast: ^7.0.2

Flutter Doctor result
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

I can run the application from android studio and debug the app. But while i want to release apk it will give me this error.

when  i run flutter build apk it gives me this error.

Thanks.

**Comment by samirkrishna** [comment]
same error bro

**Comment by ponnamkarthik** [comment]
Fixed in `7.1.0`
