### ISSUE TITLE
Error: No named parameter with the name 'timeInSecForIos'.  for building Android application

### ISSUE THREAD

**Issue by SuperApollo** [ponnamkarthik/FlutterToast#215]
lib/main.dart:111:17: Error: No named parameter with the name 'timeInSecForIos'.
                timeInSecForIos: 1,
                ^^^^^^^^^^^^^^^
../../../flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.0.2/lib/fluttertoast.dart:18:23: Context: Found this candidate, but the arguments don't match.
  static Future<bool> showToast(
                      ^^^^^^^^^

FAILURE: Build failed with an exception.

**Comment by ponnamkarthik** [comment]
change `timeInSecForIos` to  `timeInSecForIosWeb`
