### ISSUE TITLE
Memory leak: static instance of FToast which holds the BuildContext

### ISSUE THREAD

**Issue by shemhazai** [ponnamkarthik/FlutterToast#223]
What is the purpose of holding a static instance of FToast with BuildContext? It seems that it isn't used anywhere and could be safely removed.

fyi: https://stackoverflow.com/questions/59179143/does-passing-buildcontext-inside-a-static-method-causes-memory-leak-in-flutter

## Mentioned code:

```
class FToast {
  BuildContext context;

  static final FToast _instance = FToast._internal();

  factory FToast(BuildContext context) {
    _instance.context = context;
    return _instance;
  }

  FToast._internal();
 ...
```

**Comment by ponnamkarthik** [comment]
Fixed in `7.1.0`
