### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by esthefany23777** [ponnamkarthik/FlutterToast#224]
Hello, I updated to the latest version (7.0.4) and I started to give problems when starting the application, I tried to change to the previous version and they kept giving me these problems...

Here is the screenshot of the error:
![image](https://user-images.githubusercontent.com/65467570/91665048-99985200-eab8-11ea-82d6-1f8047e038cc.png)

**Comment by nicolasvac** [comment]
I'm having the same issue

**Comment by ponnamkarthik** [comment]
@elaishane 

please try 

```
flutter clean
flutter update
```

for your log i can see its point to two different versions of the same plugin

**Comment by elaishane** [comment]
Whenever I get this pub cache issue. I generally try to clear the cache by doing flutter pub cache repair

**Comment by elaishane** [comment]
> @elaishane
> 
> please try
> 
> ```
> flutter clean
> flutter update
> ```
> 
> for your log i can see its point to two different versions of the same plugin

I think you replied to the wrong person. He is @esthefany23777 and you have replied to @elaishane i.e. me

**Comment by luckbuff** [comment]
I'm having the same issue

**Comment by esthefany23777** [comment]
Hello, it's already solved, I just put

  `  flutter clean  `

and ready...
