### ISSUE TITLE
Circular borders are gone in android.

### ISSUE THREAD

**Issue by andersonmendesdev** [ponnamkarthik/FlutterToast#225]
I upgraded to version 7.0.4 and the circular borders are gone. Now is it necessary to customize the borders?

`Fluttertoast.showToast(
msg: 'Salvo!',
toastLength: Toast.LENGTH_SHORT,
backgroundColor: Colors.green,
gravity: ToastGravity.TOP,
textColor: Colors.white);`

**Comment by ponnamkarthik** [comment]
@andersonmendesdev Unable to reporocude the issue with my device i get more info about it.

**Comment by hrishikesh2007** [comment]
Same issue here. Below is my code and screenshot.

    void _showToast(String receivedText){
    Fluttertoast.showToast(
        msg: receivedText,
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
        timeInSecForIosWeb: 1,
        backgroundColor: dayThemeFlag ? dayOffWhite : midnightGreyLight,
        textColor: dayThemeFlag ? midnightGrey : dayWhite,
        fontSize: 12
      );
    }

![Untitled](https://user-images.githubusercontent.com/64446834/94083271-b8a9ab80-fdfa-11ea-89bc-99fc852dae52.jpg)

**Comment by JAICHANGPARK** [comment]
I had same Issues in Android
