### ISSUE TITLE
The error during building release AAR

### ISSUE THREAD

**Issue by relaxedSoul** [ponnamkarthik/FlutterToast#229]
Hello everyone!

I have an issue while building the release APK file.
The message: 

```
Building plugin fluttertoast...
Running Gradle task 'assembleAarRelease'...                         3.3s

e: /Users/melcore/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.0.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt: (4, 28): Unresolved reference: NonNull

FAILURE: Build failed with an exception.
```

I have the plugin installed with the following version: 
```fluttertoast: ^7.0.2```

I checked the file referenced file `FlutterToastPlugin.kt` and found unused `import androidx.annotation.NonNull`

Can you remove it? 
Or can anyone explain to me how I can ignore this error?

**Comment by ponnamkarthik** [comment]
#214
