### ISSUE TITLE
java.lang.Exception: denglibo Toast callstack! strTip=click

### ISSUE THREAD

**Issue by zhengbiwenxs** [ponnamkarthik/FlutterToast#232]
Performing hot reload...
Syncing files to device NX627J...
Reloaded 5 of 1193 libraries in 961ms.
W/System.err( 2499): java.lang.Exception: denglibo Toast callstack! strTip=click
W/System.err( 2499): 	at android.widget.Toast.show(Toast.java:127)
W/System.err( 2499): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:81)
W/System.err( 2499): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err( 2499): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err( 2499): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err( 2499): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 2499): 	at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 2499): 	at android.os.Looper.loop(Looper.java:122)
W/System.err( 2499): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 2499): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2499): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 2499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err( 2499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/EGL_adreno( 2499): tid 2550: eglSurfaceAttrib(1319): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer( 2499): Failed to set EGL_SWAP_BEHAVIOR on surface 0xb47f52a0, error=EGL_BAD_MATCH
D/EGL_adreno( 2499): eglMakeCurrent: 0xaf034d00: ver 3 1 (tinfo 0xaf039450)
D/EGL_adreno( 2499): eglMakeCurrent: 0xaf034d00: ver 3 1 (tinfo 0xaf039450)

**Comment by ponnamkarthik** [comment]
@zhengbiwenxs i was unable to reproduce the issue can you provide more details and if possible provide the sample code

**Comment by Neoqee** [comment]
@ponnamkarthik  i also get these msg, just use like this : Fluttertoast.showToast(msg: 'click a button');

**Comment by ponnamkarthik** [comment]
@Neoqee Not sure about the error may be hardware specific issue 

their is not much information available about the error on internet

**Comment by lidakai** [comment]
![image](https://github.com/ponnamkarthik/FlutterToast/assets/23355645/366eede3-b545-4bdb-ba24-1f569b6ebd95)

我也遇到了类似问题
