### ISSUE TITLE
ToastGravity.BOTTOM is too close to the bottom!

### ISSUE THREAD

**Issue by caoyanglee** [ponnamkarthik/FlutterToast#236]
is there any config param to adjust the position of the toast after setup toastGravity!

**Comment by BRAVE2HEART** [comment]
巧了，我正好也有这个需求，在想自己Fork，去改了源码算了，哈哈哈。

**Comment by ponnamkarthik** [comment]
@caoyanglee @BRAVE2HEART If you are using `FToast` hen you have access to position builder where you can set the position any where in the screen

```dart
fToast.showToast(
        child: toast,
        toastDuration: Duration(seconds: 2),
        positionedToastBuilder: (context, child) {
          return Positioned(
            child: child,
            top: 16.0,
            left: 16.0,
          );
        });
```

**Comment by BRAVE2HEART** [comment]
@ponnamkarthik Thanks !
