### ISSUE TITLE
Still getting an error with the new release

### ISSUE THREAD

**Issue by tonini46** [PonnamKarthik/FlutterToast#24]
This error shows up when i try to build my project
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

**Comment by siteslave** [comment]
Me too.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)
```

Flutter:

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[✓] VS Code (version 1.28.0)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by Conghdos** [comment]
Me too. All version don't work)

**Comment by ai930** [comment]
Me too. All version don't work)

* Error running Gradle:
Exit code 1 from: E:\\Project\cc\android\gradlew.bat app:properties:
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.2) for Android Gradle Plugin 3.2.0.
Android SDK Build Tools 28.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s


Please review your Gradle project setup in the android/ folder.

**Comment by jkyeo** [comment]
same here

**Comment by domchikdev** [comment]
same here

**Comment by GreendaMi** [comment]
same……

**Comment by andraus** [comment]
Hi all,

I had the same problem. I fixed it by updating a few version strings in my project:

`android/app/build.gradle` file:
`compileSdkVersion 28`

`android/build.gradle` file: 
`classpath 'com.android.tools.build:gradle:3.2.0'`
`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71'`

`android/gradle/wrapper/gradle-wrapper.properties` file:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

**Comment by CarGuo** [comment]
2.0.7  workaround .  

make sure the version in your `pubspec.lock` and `pubspec.yaml`

**Comment by magiccd** [comment]
same here, solved with version 2.0.7, thank you!@CarGuo

**Comment by domchikdev** [comment]
I am with version 2.0.7 and it doesn't work for me. What else can be missing? Thank you

**Comment by jamesbenCN** [comment]
still in 2.0.9





Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\Administrator\AndroidStudioProjects\esma\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by PonnamKarthik** [comment]
Please check with v2.1.0 and let me know if still exists

**Comment by siteslave** [comment]
> Please check with v2.1.0 and let me know if still exists

Wow, fixed.
