### ISSUE TITLE
Toast with no context (Duration)

### ISSUE THREAD

**Issue by andersonmendesdev** [ponnamkarthik/FlutterToast#240]
Is it not possible to have a variable to control the duration in toast without context?

**Comment by phijma** [comment]
You could use `toastLength: Toast.LENGTH_SHORT` as a parameter. Although it seems to have only two options: long or short...

**Comment by andersonmendesdev** [comment]
Thanks for the answer, I was aware of this variable, I wanted something longer in my application. But if the behavior without owes to android then it is right.

**Comment by ponnamkarthik** [comment]
Android Toast doesn't allow sec as the length it is limited to LENGTH_SHORT and LENGTH_LONG
