### ISSUE TITLE
Error: cannot find symbol     flutterEngine.getPlugins().add(new io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin());                                                                                  ^

### ISSUE THREAD

**Issue by chinkysight** [ponnamkarthik/FlutterToast#243]
I was working fine till yesterday, when I ran my app today, I start getting crashes with this error:
```
/home/chinkysight/Desktop/Bookish/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:16: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin());
                                                                                 ^
  symbol:   class FlutterToastPlugin
  location: package io.github.ponnamkarthik.toast.fluttertoast
1 error

FAILURE: Build failed with an exception.
```
I have tried by deleting the package and its caches and still I facing the problem.

**Comment by ponnamkarthik** [comment]
Unable to reproduce the issue

**Comment by chinkysight** [comment]
@ponnamkarthik  I don't know how to reproduce this issue, it was working fine but suddenly it start pop up :(

**Comment by Mastersam07** [comment]
I am also facing this issue. Installed fluttertoast: ^7.1.6 app crashes with this issue. Removed the version number and pub get. The issue persisted.

**Comment by Mastersam07** [comment]
@chinkysight did you get past this issue?

**Comment by Mastersam07** [comment]
Flutter version: 1.22.4
channel: stable
fluttertoast: ^7.1.6 (tried removing the version number but same issue)

**Comment by chinkysight** [comment]
> @chinkysight did you get past this issue?

Nope! that's why I switched to [toast](https://pub.dev/packages/toast)

**Comment by narimetisaigopi** [comment]
@Akshay-akkay it worked for me.

**Comment by Krishnabh-Das** [comment]
I also got the issue
But after trying with multiple techniques, this worked

Check out the Terminals codes in my blog
https://medium.com/@krishnabhdas3/issue-flutterengine-getplugins-add-new-827c3766499c
