### ISSUE TITLE
PlatformException(error, lateinit property mToast has not been initialized,

### ISSUE THREAD

**Issue by dineshsheoran24** [ponnamkarthik/FlutterToast#244]
E/flutter (11285): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, lateinit property mToast has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property mToast has not been initialized
E/flutter (11285): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:86)
E/flutter (11285): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (11285): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (11285): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (11285): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11285): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (11285): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (11285): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/flutter (11285): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11285): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/flutter (11285): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by altush1983** [comment]
Possible duplicate with https://github.com/ponnamkarthik/FlutterToast/pull/231

**Comment by ponnamkarthik** [comment]
Fixed with PR #231
