### ISSUE TITLE
New version of package and android default background and text color

### ISSUE THREAD

**Issue by giacomok** [ponnamkarthik/FlutterToast#245]
I was using version 4.0.1 and toasts had default Android colors (background, text color, alpha and rounded corners) for toasts.

I tried to upgrade to last version and I found out that these values are not present anymore. The default background color is transparent, the rounded corners are different from previous version.  
The last version to me is totally unusable.

I came back to version 4.0.1 and I do not think I will upgrade soon.

**Comment by ponnamkarthik** [comment]
hello @giacomok can you please check with latest version `7.1.2` 

Thanks

**Comment by giacomok** [comment]
Same :(

This is the code I use:

    Fluttertoast.showToast(
        msg: AppLocalizations.of(context).recoverPasswordAccepted,
        toastLength: Toast.LENGTH_LONG,
        gravity: ToastGravity.BOTTOM,
        timeInSecForIosWeb: 5,
        //backgroundColor: Colors.red,
        //textColor: Colors.white,
        fontSize: 16.0);

and the result is the image I attached.

![Screenshot](https://user-images.githubusercontent.com/16156317/99871099-29d9c500-2bd8-11eb-942c-fda8e973bb12.png)

The text is still white and the backround is transparent.

**Comment by ponnamkarthik** [comment]
Hello @giacomok 

Thanks for your quick response fixed the issue in `7.1.3`
