### ISSUE TITLE
 private lateinit var mToast: Toast has a bug，First do FlutterToast.cancel when not init mToast.

### ISSUE THREAD

**Issue by chenguo4930** [ponnamkarthik/FlutterToast#246]

**Comment by chenguo4930** [comment]
`  "cancel" -> {
                mToast.cancel()
                result.success(true)
            }

need:
  "cancel" -> {
              if(kotlin check init){
                mToast.cancel()
                result.success(true)
              }
            }`

**Comment by ponnamkarthik** [comment]
Duplicate of #244
