### ISSUE TITLE
Native打包问题

### ISSUE THREAD

**Issue by lizaihao** [ponnamkarthik/FlutterToast#247]
没有assets目录就不要加以下代码，谢谢，虽然不影响flutter运行，但影响native打包，native打包会报这个文件找不到
assets:
    - packages/fluttertoast/assets/

**Comment by cikichen** [comment]
`unable to find directory entry in pubspec.yaml:flutter\.pub-cache\hosted\pub.flutter-io.cn\fluttertoast-7.1.2\packages\fluttertoast\assets\

应该是同一个问题
