### ISSUE TITLE
Error: unable to find directory entry in pubspec.yaml

### ISSUE THREAD

**Issue by cikichen** [ponnamkarthik/FlutterToast#248]
`Error: unable to find directory entry in pubspec.yaml:flutter\.pub-cache\hosted\pub.flutter-io.cn\fluttertoast-7.1.2\packages\fluttertoast\assets\ `

`Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)`

**Comment by ariefwijaya** [comment]
Same issue here

**Comment by jagadish-pattanaik** [comment]
yeah same here, i have found it, its because the assets folder is inside the lib folder it should be under the root folder
