### ISSUE TITLE
Background color is invalid on ios

### ISSUE THREAD

**Issue by limuyang2** [PonnamKarthik/FlutterToast#25]
Android is Normal style，but Invalid on ios
![ios](https://i.loli.net/2018/10/14/5bc2fe241ebb5.png)  
![Android](https://i.loli.net/2018/10/14/5bc2feac58b8d.png)

**Comment by lifenautjoe** [comment]
Same problem here.

**Comment by JB-CHAUVIN** [comment]
Same, I doesn't change on IOS...

**Comment by bravekingzhang** [comment]
because ,author 
![image](https://user-images.githubusercontent.com/4476322/48877321-b876a880-ee3d-11e8-898a-70b3a6a98a75.png)
 notImplemented

**Comment by PonnamKarthik** [comment]
I am setting a crash if I implemented with the above code so I have commented it.

I am trying to fix the issue this feature will be available soon.

**Comment by PonnamKarthik** [comment]
Fixed in latest version
