### ISSUE TITLE
Redeclaration: FlutterToastPlugin

### ISSUE THREAD

**Issue by cikichen** [ponnamkarthik/FlutterToast#251]
```
e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt: (10, 14): Redeclaration: FlutterToastPlugin
e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileReleaseKotlin'.
> Compilation error. See log for more details
```

**Comment by blackkara** [comment]
e: /Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.2/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl
e: /Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by gabeaventh** [comment]
try commands below, i fixed just by doing those steps

```
flutter clean && flutter packages get

flutter build apk

or

flutter clean && flutter build apk
```

**Comment by gabeaventh** [comment]
> ```
> e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt: (10, 14): Redeclaration: FlutterToastPlugin
> e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':fluttertoast:compileReleaseKotlin'.
> > Compilation error. See log for more details
> ```


try commands below, i fixed just by doing those steps

```
flutter clean && flutter packages get

flutter build apk

or

flutter clean && flutter build apk
```

**Comment by cikichen** [comment]
> > ```
> > e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt: (10, 14): Redeclaration: FlutterToastPlugin
> > e: flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-7.1.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':fluttertoast:compileReleaseKotlin'.
> > > Compilation error. See log for more details
> > ```
> 
> try commands below, i fixed just by doing those steps
> 
> ```
> flutter clean && flutter packages get
> 
> flutter build apk
> 
> or
> 
> flutter clean && flutter build apk
> ```

It will happen if multiple versions exist in the pub cache
