### ISSUE TITLE
fluttertoast web Flutter 1.23.0-1.8.1.pre #bug ? Not showing on web build

### ISSUE THREAD

**Issue by ConnorMcDonough** [ponnamkarthik/FlutterToast#254]
Hello! I am using fluttertoast on web and it works fine in debug mode
![image](https://user-images.githubusercontent.com/23460425/100526411-b535f600-3196-11eb-881e-d83bab063c63.png)

but when I try to build the project (flutter build web command) the toast won't show up! Am I doing something wrong? Or just a bug I cant workaround?

code
```
} else if(emailController.text == "" ||passwordController.text == "") {
                      Fluttertoast.showToast(
                          msg: "Email or password are empty!",
                          webPosition: "center",
                          webBgColor: "#000000",
                          toastLength: Toast.LENGTH_LONG);
                    } else if(emailController.text != emailControllerRetype.text ||passwordController.text != passwordControllerRetype.text) {
                      Fluttertoast.showToast(
                          msg: "Email or password do not match!",
                          webPosition: "center",
                          webBgColor: "#000000",
                          toastLength: Toast.LENGTH_LONG);
                    }
```

Thanks,

**Comment by mishatron** [comment]
the same for me. got an error: Uncaught ReferenceError: Toastify is not defined

**Comment by shatanikmahanty** [comment]
I had the same problem before but it was fixed in 
  fluttertoast: ^7.1.5
Make sure you are using : 
 ` fluttertoast: ^7.1.5`
If it doesn't work try running `flutter clean` and then ` flutter pub get` and see if it gets fixed
