### ISSUE TITLE
FlutterToast throws MethodCallHandlerImpl while building project

### ISSUE THREAD

**Issue by blackkara** [ponnamkarthik/FlutterToast#256]
The version i'm trying to use is `fluttertoast: ^7.1.5`. It's added, but fails while building/running with below two logs

`/Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.2/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl`

`/Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl`

- Cache is cleaned lots of times
- Other dependencies can be added/removed without any problem

But project is unable to have this FlutterToast.

Any suggestion ?

**Comment by iamwilph** [comment]
fixed mine by adding **multiDexEnabled true** in android/build file

defaultConfig {
    minSdkVersion 15 
    targetSdkVersion 28
    ...
    multiDexEnabled true
}

**Comment by ponnamkarthik** [comment]
try visit this path from finder `/Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/` and delete folder `fluttertoast-7.1.2`

then try

**Comment by blackkara** [comment]
> try visit this path from finder `/Users/macbook/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/` and delete folder `fluttertoast-7.1.2`
> 
> then try

Thats absolute cure for me!
