### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [ponnamkarthik/FlutterToast#257]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:fluttertoast

For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by ponnamkarthik** [comment]
@AndroidIosWebEmbeddedFirmwareDver  Working on null-safety will release soon
