### ISSUE TITLE
Add custom position to default toast

### ISSUE THREAD

**Issue by Fintasys** [ponnamkarthik/FlutterToast#259]
I have started to use this library, but I was kinda disappointed that position for `ToastGravity.TOP` is too high (over navbar) and `ToastGravity.BOTTOM` too low. I understand that I can set custom position by creating a custom implementation. But for just changing the position it's way too much effort IMHO. Why not provide optional attribute to set `Positioned`-Widget? 

Thank you very much and appreciate your works 🙇

**Comment by ponnamkarthik** [comment]
```dart
// Custom Toast Position
    fToast.showToast(
        child: toast,
        toastDuration: Duration(seconds: 2),
        positionedToastBuilder: (context, child) {
          return Positioned(
            child: child,
            top: 16.0,
            left: 16.0,
          );
        });
```

https://github.com/ponnamkarthik/FlutterToast#toast-with-buildcontext

**Comment by Fintasys** [comment]
It still needs the custom implementation of `child: toast`. That's not what I proposed :( 
More like 
``` 
Fluttertoast.showToast(
        msg: "This is Center Short Toast",
        toastLength: Toast.LENGTH_SHORT,
      positionedToastBuilder: (context, child) {
          return Positioned(
            child: child,
            top: 16.0,
            left: 16.0,
          );
        });
```

**Comment by ponnamkarthik** [comment]
@Fintasys got it will need to implement another function like this `Fluttertoast.showSimpleToast` i will work on it and push an update

**Comment by itsdani121** [comment]
hi , i want to change position of toast in flutter web and app , so how i can do that when it run on web it change their position and on mobile app it position remain default
