### ISSUE TITLE
A problem occurred configuring project ':fluttertoast'.

### ISSUE THREAD

**Issue by isoos** [PonnamKarthik/FlutterToast#26]
_From @1420965446 on October 29, 2018 9:55_

I just added a line :   fluttertoast: ^2.0.9

* Error running Gradle:
Exit code 1 from: /Users/edz/Desktop/flutter_app/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Finished with error: Please review your Gradle project setup in the android/ folder.

_Copied from original issue: dart-lang/pub-dartlang-dart#1731_

**Comment by manondidi** [comment]
i have same problem

**Comment by manondidi** [comment]
* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

**Comment by yanftch** [comment]
the same issue with me. got this error message when I running with my Android Phone.

**Comment by PonnamKarthik** [comment]
Please try with version 2.1.0 and let me know the result

**Comment by yanftch** [comment]
> Please try with version 2.1.0 and let me know the result

just check with the latest version, works fine
