### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by KaungZawHtet** [ponnamkarthik/FlutterToast#260]
Here is the error from debub console

`/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (16, 16): Redeclaration: MethodCallHandlerImpl`

**Comment by shatanikmahanty** [comment]
Can you try `flutter clean` on project and then `flutter pub get` and then check if it works.

**Comment by KaungZawHtet** [comment]
Yes, I think it gone now

**Comment by Rissmon** [comment]
I have the issue even after `flutter clean` on project

**Comment by shatanikmahanty** [comment]
> I have the issue even after `flutter clean` on project

@Rissmon are you using the latest version?

**Comment by Rissmon** [comment]
I was able to fix the issue by upgrading the distribution URL and Gradle versions.

- Updated the distribution URL in

`android/gradle/wrapper/gradle-wrapper.properties`
```

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip

```
-Updated gradle version in build.gradle

```
dependencies {
        classpath "com.android.tools.build:gradle:4.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```
@shatanikmahanty Thanks for the quick response.

**Comment by shatanikmahanty** [comment]
> I was able to fix the issue by upgrading the distribution URL and Gradle versions.
> 
> * Updated the distribution URL in
> 
> `android/gradle/wrapper/gradle-wrapper.properties`
> 
> ```
> 
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
> ```
> 
> -Updated gradle version in build.gradle
> 
> ```
> dependencies {
>         classpath "com.android.tools.build:gradle:4.2.1"
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> ```
> 
> Hope this will work for everyone.
> @shatanikmahanty Thanks for the quick response.

You are welcome @Rissmon . Happy to help
