### ISSUE TITLE
How do you test flutter toast messages?

### ISSUE THREAD

**Issue by joshbrookstone** [ponnamkarthik/FlutterToast#262]
I cant seem to figure out how to test my toast message. If I run it on a flutter emulator in the test then i know that the toast is showing up. I just don't know how to exactly target the toast. is there a method that you have been using in your own tests?

**Comment by ponnamkarthik** [comment]
i have no test cases, 

we cannot test FlutterToast without buildcontext as it details with the native side

but you can write test cases for Toast with BuildContext as it use flutter widgets to display toast

**Comment by PWrzesinski** [comment]
In case someone finds this thread in the future, as I did, you can add a key to your toast's content and test using something like:

    final finder = find.byKey(your_key);
    final Duration timeout = const Duration(milliseconds: 500);
    final DateTime start = DateTime.now();
    while (DateTime.now().difference(start) < timeout) {
      if (tester.any(finder)) {
        break;
      }
      await tester.pump(const Duration(milliseconds: 10));
    }

    if (!tester.any(finder)) {
      fail("Toast not found");
    }
