### ISSUE TITLE
how to change toast style ?

### ISSUE THREAD

**Issue by YDJSZY** [PonnamKarthik/FlutterToast#27]
how to change border-radius ?

**Comment by PonnamKarthik** [comment]
Right not its not possible

**Comment by TopGuo** [comment]
bgcolor可以不用string类型吗？能不能弄成接受Flutter里Colors这个类

**Comment by TopGuo** [comment]
> @TopGuo Please check the latest version now you can use Colors Class from Flutter

Ok thank you.
this version 2.1.4 use Colors.
