### ISSUE TITLE
Error on assembleDebug

### ISSUE THREAD

**Issue by jonbhanson** [ponnamkarthik/FlutterToast#272]
I am getting a new error when I try to build my app:

```
e: /Users/jonhanson/Projects/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (45, 84): Unresolved reference: R
e: /Users/jonhanson/Projects/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (70, 68): Unresolved reference: R
e: /Users/jonhanson/Projects/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (85, 64): Unresolved reference: R

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
```

I think the only change that I made was to update the [Kotlin plugin](https://plugins.jetbrains.com/plugin/6954-kotlin).  Maybe this error is related to that?

Edit: Note that the problem is on flutter_toast version 7.1.8.

**Comment by jonbhanson** [comment]
I'm not sure why, but I was able to resolve the problem by rolling back to 
```
classpath 'com.android.tools.build:gradle:3.5.4'
```
in my top level `build.gradle`.

**Comment by proninyaroslav** [comment]
Same here.

**Comment by proninyaroslav** [comment]
I rolled back to `7.1.6` because `7.1.7` and `7.1.8` have this problem.

**Comment by NaikSoftware** [comment]
![image](https://user-images.githubusercontent.com/4218994/109437114-e17a4080-7a2b-11eb-88c7-72fdf4d2ccd3.png)
https://developer.android.com/studio/releases/gradle-plugin

**Comment by NaikSoftware** [comment]
Its because you need compileSdkVersion 30 or highter for 'O' constant

**Comment by jonbhanson** [comment]
Thanks @NaikSoftware, updating the compileSdkVersion to 30 in my app/build.gradle solved it for me. 👍🏻
