### ISSUE TITLE
no-context not working in Android 11 (API 30)

### ISSUE THREAD

**Issue by jonbhanson** [ponnamkarthik/FlutterToast#273]
I had trouble with the no-context toast, so I tested the example in the package.  As shown in the image below, the center setting for the no-context toast is not centering the toast.  To reproduce, simply run the example.  Android version 11 on Pixel 2 XL.

Update: On an emulated Android 10 (API 29) Pixel XL, the toasts work fine, so it seems the problem started with Android 11 (API 30). The problem is on flutter_toast version 7.1.8.

![Screenshot_20210222-152727](https://user-images.githubusercontent.com/32202698/108768256-6db8cf00-7525-11eb-8738-82170e6267f3.png)

**Comment by AlexHurray** [comment]
Same problem...

**Comment by Sathi789888** [comment]
I am getting this same issue when upgrade the android 11.

**Comment by ponnamkarthik** [comment]
Check with `8.0.4`

**Comment by jonbhanson** [comment]
Still having the problem.  To reproduce, in android/app/build.gradle, change the `targetSdkVersion` to `30`.  The Center Short Toast is not centered.

**Comment by ponnamkarthik** [comment]
as of android 30 they have changed the way toast renders and they deprecated some methods 

the reason for gravity not working is they as ignoring the value if target sdk is >= 30 check docs for more info

```
Warning: Starting from Android Build.VERSION_CODES#R, for apps targeting API level Build.VERSION_CODES#R or higher, this method is a no-op when called on text toasts.
```

https://developer.android.com/reference/android/widget/Toast#setGravity(int,%20int,%20int)
