### ISSUE TITLE
android7 android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by Silence17136** [ponnamkarthik/FlutterToast#275]
android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@61726d3 is not valid; is your activity running?
android.view.ViewRootImpl.setView(ViewRootImpl.java:679)

android 7 toast兼容问题是否有解决？

**Comment by 385841539** [comment]
解决了么？这个恒安个啊
