### ISSUE TITLE
please add desktop support 

### ISSUE THREAD

**Issue by kechankrisna** [ponnamkarthik/FlutterToast#280]
MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast) on desktop support

**Comment by ponnamkarthik** [comment]
for Desktops we need to use toast with buildcontext - which supports all platforms.

https://pub.dev/packages/fluttertoast#toast-with-buildcontext-all-platforms

i will try to sync the toast without context to  toast with buildcontext so it will works with any platform
