### ISSUE TITLE
Null safety and flutter 2

### ISSUE THREAD

**Issue by ammaratef45** [ponnamkarthik/FlutterToast#282]
Please upgrade to support null safety and flutter2

**Comment by innwin** [comment]
I also need

**Comment by ponnamkarthik** [comment]
<img width="687" alt="Screenshot 2021-03-21 at 9 53 51 AM" src="https://user-images.githubusercontent.com/19759716/111893824-6bb23500-8a2b-11eb-9c00-df6ff2804815.png">

already has a null-safe version will merge it soon to one
