### ISSUE TITLE
v7.1.7 update compileSdkVersion to 30, as would break many project builds

### ISSUE THREAD

**Issue by macarthor** [ponnamkarthik/FlutterToast#283]
as the title says. many projects compile against SDKs below 30.

**Comment by ctedgar** [comment]
> as the title says. many projects compile against SDKs below 30.

+1

**Comment by Canoir** [comment]
Hi,
I have version 30 compileSDKVersion and my build is breaking, I really have to remove all flutter_toast libs in my projects!

**Comment by ponnamkarthik** [comment]
Fixed in `8.0.4`

**Comment by Canoir** [comment]
> Fixed in `8.0.4`

Hi, I have tested out v8.0.4 and the error was not solved!

**Comment by Jobayerdev** [comment]
> 8.0.4

Yet I'm getting the same error
