### ISSUE TITLE
Execution failed for task ':fluttertoast:compileDebugKotlin'.  Andriod compilation failed.

### ISSUE THREAD

**Issue by snlo** [ponnamkarthik/FlutterToast#284]
e: /Users/snloveydus/Desktop/flutter_app/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (45, 84): Unresolved reference: R
e: /Users/snloveydus/Desktop/flutter_app/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (70, 68): Unresolved reference: R
e: /Users/snloveydus/Desktop/flutter_app/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (85, 64): Unresolved reference: R
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':fluttertoast:compileDebugKotlin'.           
> Compilation error. See log for more details

**Comment by choi-seung-min** [comment]
I've got same error.

**Comment by macarthor** [comment]
do either:
1. upgrade your compileSdkVersion to 30
2. change dependency of fluttertoast to exact 7.1.6

**Comment by snlo** [comment]
@macarthor Thank you，

**Comment by AshishInnovantes** [comment]
I have got the same error.

**Comment by ctedgar** [comment]
> I have got the same error.

+1

**Comment by mstrkn** [comment]
> I have got the same error.

+1

**Comment by Khaleesi-sb** [comment]
I got the same error.  This solved my problem. 
1. pubspec.yaml -->> pub upgrade 
2. Change `fluttertoast` version to latest 
3. Pub get
4. Run...

**Comment by Muhammad-Tayyab67** [comment]
same problem

**Comment by lukeirvin** [comment]
I'm getting this issue after updating to Flutter 3.29.2
