### ISSUE TITLE
This problem is coming after dart migration....

### ISSUE THREAD

**Issue by dev-sahir** [ponnamkarthik/FlutterToast#285]
![grad](https://user-images.githubusercontent.com/80703543/111804400-3fe36200-88fa-11eb-90c1-6c9c9876cd0d.jpg)

**Comment by ponnamkarthik** [comment]
try doing a flutter clean and them build

**Comment by muhammadkamel** [comment]
I am facing the same issue. And I tried "flutter clean" and rebuild. Doesn't work.

**Comment by macarthor** [comment]
solution in #284

**Comment by ctedgar** [comment]
> I am facing the same issue. And I tried "flutter clean" and rebuild. Doesn't work.

+1
