### ISSUE TITLE
backgroundColor does not work

### ISSUE THREAD

**Issue by 2013612** [ponnamkarthik/FlutterToast#286]
I try to set the backgroundColor to different colors but it does not work.
![Screenshot_1616324002](https://user-images.githubusercontent.com/10905640/111902136-d0df4800-8a76-11eb-9120-d07119b6f32a.png)

my code:
![image](https://user-images.githubusercontent.com/10905640/111902145-e0f72780-8a76-11eb-86c5-141bb0e6a912.png)

I am working on Android 11, fluttertoast: ^8.0.3

**Comment by ponnamkarthik** [comment]
https://github.com/ponnamkarthik/FlutterToast#note-android

**Comment by JosephNK** [comment]
@ponnamkarthik 

i try https://github.com/ponnamkarthik/FlutterToast#note-android

is not work :( 

<img width="362" alt="2021-04-23 3 40 48" src="https://user-images.githubusercontent.com/1622085/115829794-5b3a1380-a44a-11eb-95a9-741df0f50cdf.png">

**Comment by ponnamkarthik** [comment]
if you are building for api version lessthan 30 it will work
