### ISSUE TITLE
on android 10 when keyboard is show ,can`t display toast.

### ISSUE THREAD

**Issue by gaoypChina** [ponnamkarthik/FlutterToast#287]
on android 10 when keyboard is show ,can`t display toast.
when close keyboard,toast is showed.

**Comment by Sominemo** [comment]
Same on Android 11

**Comment by WieFel** [comment]
+1

**Comment by SAGARSURI** [comment]
Even I am facing the same issue. @ponnamkarthik

**Comment by ponnamkarthik** [comment]
Fixed in `8.0.7`
