### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?

### ISSUE THREAD

**Issue by iderizemathan** [ponnamkarthik/FlutterToast#298]
Not working in Android

**Comment by xappteam** [comment]
Not working in Android too, please check, thanks

**Comment by ShakeebIqbal** [comment]
/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (129, 28): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?

**Comment by msthoma** [comment]
Same issue here, seems to affect versions 8.0.4 and 8.0.5. Until this is fixed, a temporary fix is to specify the last working version as an exact dependency (without ^):
`fluttertoast: 8.0.3`

**Comment by ShakeebIqbal** [comment]
> Same issue here, seems to affect versions 8.0.4 and 8.0.5. Until this is fixed, a temporary fix is to specify the last working version as an exact dependency (without ^):
> `fluttertoast: 8.0.3`

same issue on

**Comment by ponnamkarthik** [comment]
Fixed in `8.0.6`
