### ISSUE TITLE
Running on android has errors

### ISSUE THREAD

**Issue by 2534290808** [PonnamKarthik/FlutterToast#30]
W/System.err(15667): java.lang.IllegalArgumentException: Unknown color
W/System.err(15667): 	at android.graphics.Color.parseColor(Color.java:235)
W/System.err(15667): 	at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:74)
W/System.err(15667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/System.err(15667): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
W/System.err(15667): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(15667): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(15667): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(15667): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err(15667): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15667): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err(15667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/System.err(15667): java.lang.IllegalArgumentException: Unknown color
W/System.err(15667): 	at android.graphics.Color.parseColor(Color.java:226)
W/System.err(15667): 	at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:88)
W/System.err(15667): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/System.err(15667): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
W/System.err(15667): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(15667): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(15667): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(15667): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err(15667): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15667): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err(15667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/art     (15667): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[14,tid=17200,Native,Thread*=0x55ccc6f020,peer=0x22d0a0a0,"Thread-16091"]

**Comment by adadion** [comment]
> W/System.err(15667): java.lang.IllegalArgumentException: Unknown color
> W/System.err(15667): at android.graphics.Color.parseColor(Color.java:235)

Can you give piece of code of your fluttertoast implementation? It seems you gave the wrong color format. See [this](https://github.com/PonnamKarthik/FlutterToast#how-to-use) on property table description.
