### ISSUE TITLE
showToast parameters have no effect in Android

### ISSUE THREAD

**Issue by hm122** [ponnamkarthik/FlutterToast#302]
When using the following code:

```
Fluttertoast.showToast(
  msg: text,
  toastLength: Toast.LENGTH_LONG,
  gravity: ToastGravity.CENTER,
  timeInSecForIosWeb: 1,
  backgroundColor: Colors.green,
  textColor: Colors.white,
  fontSize: 16.0
);
```
I'm getting a gray toast with black text located on the bottom of the screen with Android. I'm using version 8.0.6. iOS works perfectly fine.

Android: 
<img width="115" alt="Screen Shot 2021-04-28 at 09 33 32" src="https://user-images.githubusercontent.com/13405226/116364823-e62d5c00-a804-11eb-8fce-8ab23fac4952.png">

iOS:
<img width="185" alt="Screen Shot 2021-04-28 at 09 33 50" src="https://user-images.githubusercontent.com/13405226/116364838-ea597980-a804-11eb-9cfe-c316a7d287ae.png">

**Comment by park1120** [comment]
same issue here!

**Comment by beagle-barks** [comment]
Same issue here on Android 10 and 11.

Might have something to do with the deprecated `setView` function in `Toast` class?

**Comment by LEMUSADR000** [comment]
@beagle-barks I'm fairly sure this is exactly what's going on. Does anybody have a working example of a custom toast?

**Comment by Ronadlo7** [comment]
old version is ok ,but new version have problem

**Comment by alanlanglois** [comment]
Same issue since the null safety update.

**Comment by ponnamkarthik** [comment]
if you are targeting android 30 then things have changed as of android 30 Toast has deprecated setView method which is used earlier to do custom toast color and radius.

and on android 30 setGravity is ignored

please check https://developer.android.com/reference/android/widget/Toast for more info

**Comment by Ronadlo7** [comment]
if setGravity is ignored on android 30 ，why no method can replace

**Comment by alanlanglois** [comment]
@ponnamkarthik strange thing is that I'm not targeting 30 but 29 instead 🤔 
`/projectname/android/app/build.gradle`

![image](https://user-images.githubusercontent.com/712986/118780875-cd0c4e00-b88c-11eb-9d62-40ae0588fbf7.png)
![image](https://user-images.githubusercontent.com/712986/118780658-91718400-b88c-11eb-9113-a1ad34a3db7c.png)

**Comment by beagle-barks** [comment]
This might be the issue @ponnamkarthik - I've built an android app without flutter, pure android, and I can confirm, at least for me:
setting to target 30 will solve the issue, even when `view` is deprecated.

**Comment by Ronadlo7** [comment]
set target 29 is useless

**Comment by ponnamkarthik** [comment]
if your android API is  < 30 it uses setView which supports background color else it just invoke system default toast

**Comment by yassine-bennkhay** [comment]
Has anyone found any solution for this issue? got into the same problem, not style effect is taken!

**Comment by nsmith1024** [comment]
Why did they remove that feature of showing the toast in the center of the screen using setGravity(...) ? I cant understand why they would force it to be displayed at the bottom of the screen where no one can see it? What the point of having a toast function and then try to hide it? It makes no sense! Do they think people constantly looking all over the screen for hidden messages that pop up for 1 second?
