### ISSUE TITLE
setGravity() shouldn't be called on text toasts

### ISSUE THREAD

**Issue by muhammadkamel** [ponnamkarthik/FlutterToast#303]
I am getting a warning "setGravity() shouldn't be called on text toasts, the values won't be used".
I am using the latest version of the package. 

Fluttertoast.showToast(
                                    msg: "Text here!",
                                    toastLength: Toast.LENGTH_SHORT,
                                    gravity: ToastGravity.BOTTOM,
                                    timeInSecForIosWeb: 1,
                                    backgroundColor: Colors.grey,
                                    textColor: Colors.white,
                                    fontSize: 16.0,
                                  );

**Comment by iekara** [comment]
I have same problem.

Thank you.

**Comment by akashvshroff** [comment]
I'm having the same issue. Thanks.

**Comment by louayyy99** [comment]
same issue here...

**Comment by fatih38** [comment]
I'm having the same issue. Thanks.

**Comment by 18691899062** [comment]
---Original---
From: ***@***.***&gt;
Date: Sat, May 15, 2021 18:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [ponnamkarthik/FlutterToast] setGravity() shouldn't be called on text toasts (#303)




 
I'm having the same issue. Thanks.

**Comment by SittiphanSittisak** [comment]
How you fix this?
How I use toast in API 30?
