### ISSUE TITLE
Package failed to build since version 8.0.2

### ISSUE THREAD

**Issue by ehabelnahas** [ponnamkarthik/FlutterToast#306]
Hello,
The package was running smoothly till the version 7.1.8, since I decided to upgrade, I found all newer versions starting from 8.0.2 to 8.0.6 are failing and causing build to terminate with the following error message:

e: D:\Programs\Flutter\flutter_2.0.1\.pub-cache\hosted\pub.dartlang.org\fluttertoast-7.1.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (17, 16): Redeclaration: MethodCallHandlerImpl
e: D:\Programs\Flutter\flutter_2.0.1\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.6\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (21, 16): Redeclaration: MethodCallHandlerImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ponnamkarthik** [comment]
Try 

flutter clean 

Then build the project
