### ISSUE TITLE
Issues when a new toast is issued during the fade-out animation of the existing toast

### ISSUE THREAD

**Issue by plavunov** [ponnamkarthik/FlutterToast#307]
Hi!

When a toast is on the screen, and it starts fading away, a new toast issued at this very moment breaks the animation and will not be displayed, or will blink for a frame. This doesn't look like desired behavior...

Also, it would be perfect if there was an option to set the opacity times for the toasts (currently it's too long)

Thank you!

**Comment by ponnamkarthik** [comment]
in `8.0.7` added new parameter fadeDuration to set the fade animation duration

**Comment by plavunov** [comment]
Thank you, but this issue remains: **When a toast is on the screen, and it starts fading away, a new toast issued at this very moment breaks the animation and will not be displayed, or will blink for a frame.** 

And it's much more important than the fade duration.
