### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mdddj** [ponnamkarthik/FlutterToast#309]
![image](https://user-images.githubusercontent.com/29020213/119067551-f6f07c80-ba14-11eb-9107-f9154bacbde3.png)

**Comment by mdddj** [comment]
fluttertoast: ^8.0.7

**Comment by chamikapeiris** [comment]
same here.

**Comment by chamikapeiris** [comment]
**Do a Gradle clean, It should work.**
```
cd android/
./gradlew clean
```

**Comment by mdddj** [comment]
> **Do a Gradle clean, It should work.**
> 
> ```
> cd android/
> ./gradlew clean
> ```

Thank you, it has been resolved
