### ISSUE TITLE
backgroundColor, gravity not working: Only simple toast is displaying.

### ISSUE THREAD

**Issue by anburocky3** [ponnamkarthik/FlutterToast#310]
Snippets i used:
```dart
Fluttertoast.showToast(
    msg: "Don't be so fast! Retry after some time.",
    toastLength: Toast.LENGTH_LONG,
    gravity: ToastGravity.CENTER,
    timeInSecForIosWeb: 1,
    backgroundColor: Colors.red,
    textColor: Colors.white,
    fontSize: 16.0);
```

**UPDATE:** It is working as expected on the physical device (Android 10). But not working on emulator (Android 11)

**Comment by eduardbraun** [comment]
Same for me, background color is not working on Android 11

**Comment by anburocky3** [comment]
Looks like, author has mentioned about it in the documentation: 

> Custom Toast will not work on android 11 and above, it will only use msg and toastLength remaining all properties are ignored

**Comment by anburocky3** [comment]
Is there any alternative ways to achieve this?

**Comment by ponnamkarthik** [comment]
You can use https://github.com/ponnamkarthik/FlutterToast#toast-with-buildcontext-all-platforms to show custom toast
