### ISSUE TITLE
Its not working in anyway

### ISSUE THREAD

**Issue by ertugrul-cakici** [ponnamkarthik/FlutterToast#311]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter (23296): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (23296): <asynchronous suspension>
E/flutter (23296): #1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:98:17)
E/flutter (23296): <asynchronous suspension>`

I got this error when I tried on my real phone and emulator. I'm new to flutter and android programming.
 
I used it through a floating action button as below
`floatingActionButton: FloatingActionButton(child: Text("Tıkla"),onPressed: (){debugPrint("sa");Fluttertoast.showToast(msg: "sa");},)`

**Comment by vinayvishnu725** [comment]
clean your project then rebuild , in terminal type  " flutter clean "
