### ISSUE TITLE
module 'fluttertoast' not found

### ISSUE THREAD

**Issue by ZeeshanJelani** [ponnamkarthik/FlutterToast#314]
fatal error: module 'fluttertoast' not found
    @import fluttertoast;
build successfully done on flutter side but this error comes on  archive time in xcode

**Comment by hetao29** [comment]
me 2

**Comment by SoorajSoman** [comment]
I just fixed it by installing cocoapod which is dependency manager for swift and objective c and then running command 

> pod deintegrate
> pod install

inside  iOS folder in the Flutter project .This should be same for what ever flutter plugin we are going to set up in the project.Please check this link as well

https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Hope this helps.

**Comment by Maadhav** [comment]
https://github.com/flutter/flutter/issues/53573#issuecomment-746532273
This fixed the issue for me...

**Comment by luupnh** [comment]
> [flutter/flutter#53573 (comment)](https://github.com/flutter/flutter/issues/53573#issuecomment-746532273) This fixed the issue for me...

That goods <3

**Comment by AkshayRPalwe** [comment]
> pod deintegrate

Worked for me

**Comment by IKTANIM** [comment]
go to IOS folder and run `Pod clean` then `pod install`
