### ISSUE TITLE
Depend on the latest Kotlin version

### ISSUE THREAD

**Issue by rocboronat** [ponnamkarthik/FlutterToast#315]
Hello there! I'm placing this issue here, but it's also a bit of a question.

As my Flutter app depends on FlutterToast and FlutterToast on Kotlin, the Kotlin runtime is embedded into my app. But as my app also depends on another version of Kotlin, both versions of Kotlin are embedded.

To add more context, this is related to this question I made on StackOverflow: https://stackoverflow.com/questions/67885993/multiple-kotlin-runtimes-in-the-same-flutter-app

So, how to fix it? Should FlutterToast depend on the latest version of Kotlin? Should I change something on my app? Maybe the solution is to stop depending on Kotlin on packages like FlutterToast, that for sure Kotlin is not thaaat needed?

Thanks a lot for the package, the answer, the time, and everything 😄

**Comment by nt4f04uNd** [comment]
You are likely hitting https://github.com/flutter/flutter/issues/95141

**Comment by rocboronat** [comment]
Thank you so much, @nt4f04uNd 😊
