### ISSUE TITLE
Toast is not centered in Android 11

### ISSUE THREAD

**Issue by andfaraway** [ponnamkarthik/FlutterToast#318]
Toast is not centered in Android 11
![file-read-936](https://user-images.githubusercontent.com/20471572/122732894-442f6a80-d2af-11eb-8323-e3a739cd441e.png)

**Comment by andfaraway** [comment]
Fluttertoast.showToast('成功');

**Comment by HannibalKcc** [comment]
> Fluttertoast.showToast('成功');

this code is invalid, maybe you should show valid code.
