### ISSUE TITLE
Fluttertoast.showToast Exception.

### ISSUE THREAD

**Issue by GreatWriter** [ponnamkarthik/FlutterToast#322]
`Fluttertoast.showToast(msg: "This is Center Short Toast");`

environment：
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.685], locale zh-CN)
    • Flutter version 2.2.2 at E:\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dxs\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\dxs\AppData\Local\Android\Sdk
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\dxs\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Redmi 5A (mobile) • 1c73cd047d44 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 91.0.864.41

Console out：
W/TypefaceUtils( 6313): getFamilyNameField failed
W/TypefaceUtils( 6313): java.lang.NoSuchFieldException: familyName
W/TypefaceUtils( 6313): 	at java.lang.Class.getField(Class.java:1601)
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.getFamilyNameField(TypefaceUtils.java:269)
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.<clinit>(TypefaceUtils.java:265)
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:524)
W/TypefaceUtils( 6313): 	at android.widget.TextView.setTypeface(TextView.java:3711)
W/TypefaceUtils( 6313): 	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2108)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:1614)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:820)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:816)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createView(LayoutInflater.java:651)
W/TypefaceUtils( 6313): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
W/TypefaceUtils( 6313): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:50)
W/TypefaceUtils( 6313): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/TypefaceUtils( 6313): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/TypefaceUtils( 6313): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/TypefaceUtils( 6313): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/TypefaceUtils( 6313): 	at android.os.MessageQueue.next(MessageQueue.java:331)
W/TypefaceUtils( 6313): 	at android.os.Looper.loop(Looper.java:149)
W/TypefaceUtils( 6313): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Method.invoke(Native Method)
W/TypefaceUtils( 6313): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/TypefaceUtils( 6313): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
W/TypefaceUtils( 6313): getFontNames failed
W/TypefaceUtils( 6313): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.getFontNames(TypefaceUtils.java:578)
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:532)
W/TypefaceUtils( 6313): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:524)
W/TypefaceUtils( 6313): 	at android.widget.TextView.setTypeface(TextView.java:3711)
W/TypefaceUtils( 6313): 	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2108)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:1614)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:820)
W/TypefaceUtils( 6313): 	at android.widget.TextView.<init>(TextView.java:816)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createView(LayoutInflater.java:651)
W/TypefaceUtils( 6313): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
W/TypefaceUtils( 6313): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
W/TypefaceUtils( 6313): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:50)
W/TypefaceUtils( 6313): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/TypefaceUtils( 6313): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/TypefaceUtils( 6313): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/TypefaceUtils( 6313): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/TypefaceUtils( 6313): 	at android.os.MessageQueue.next(MessageQueue.java:331)
W/TypefaceUtils( 6313): 	at android.os.Looper.loop(Looper.java:149)
W/TypefaceUtils( 6313): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
W/TypefaceUtils( 6313): 	at java.lang.reflect.Method.invoke(Native Method)
W/TypefaceUtils( 6313): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/TypefaceUtils( 6313): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
I/Toast   ( 6313): Show toast from OpPackageName:com.flutter.wuxianyuedu, PackageName:com.flutter.wuxianyuedu
W/Adreno-EGL( 6313): <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
D/vndksupport( 6313): Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
W/Adreno-ES20( 6313): <core_glFinish:34>: glFinish skipped: 0
W/Adreno-ES20( 6313): <core_glFinish:34>: glFinish skipped: 0

**Comment by ponnamkarthik** [comment]
please provide a example code to reproduce the issue
