### ISSUE TITLE
Failed assertion: line 147 pos 12: '_overlay != null': is not true.

### ISSUE THREAD

**Issue by Jason-zzzz** [ponnamkarthik/FlutterToast#323]
when execute removeCustomToast() or removeQueuedCustomToasts() and run to this line :
 if (_entry != null) _entry!.remove(); /// there _entry is not null ,but _entry._overlay is null , and will assert(_overlay != null);

_entry = {OverlayEntry} OverlayEntry#1dab3(opaque: false; maintainState: false)
 _listeners = {LinkedList} ()
 builder = {_Closure} Closure: (BuildContext) => Widget
 _opaque = false
 _maintainState = false
 _mounted = false
 _overlay = null
 _key = {LabeledGlobalKey} [LabeledGlobalKey<_OverlayEntryWidgetState>#893ed]

**Comment by Jason-zzzz** [comment]
![image](https://user-images.githubusercontent.com/16592298/124733919-39c7ce80-df47-11eb-8fa8-c50ab0b0858f.png)

**Comment by ponnamkarthik** [comment]
fixed in code will update in new version
