### ISSUE TITLE
Setting the background color to white, will show black background on android

### ISSUE THREAD

**Issue by itadminmynapse** [ponnamkarthik/FlutterToast#325]
When the showtoast is called with background color set to white, on android (instead of white) a black background will be displayed. On iOS the background is okay (white)

**Comment by ponnamkarthik** [comment]
If you are using https://github.com/ponnamkarthik/FlutterToast#toast-with-no-build-context-android--ios and your target sdk is 30 then plugin ignores colors it just shows the default toast for android
