### ISSUE TITLE
background color and font color are not working latest version.

### ISSUE THREAD

**Issue by phanindravarma412** [ponnamkarthik/FlutterToast#328]

**Comment by XanderSelorm** [comment]
On android 11, background color and gravity do not seem to work.
I tested it with Samsung A22

**Comment by Ahemad7429** [comment]
I am also facing the same issue in one plus 7 pro and 8 pro.

**Comment by mfuenzalida1** [comment]
I am having the same issue on android 11

**Comment by C4st3ll4n** [comment]
Still having problems with the background color on android 11.
The background color should be red.

![image](https://user-images.githubusercontent.com/27224139/128667962-c2aa52d4-934e-465a-b436-1c097b0f5cf9.png)

**Comment by xahid71** [comment]
same here!

**Comment by yaochangliang159** [comment]
same here!

**Comment by cs-hyunseo** [comment]
Any changes?
