### ISSUE TITLE
bgColor bug

### ISSUE THREAD

**Issue by TopGuo** [PonnamKarthik/FlutterToast#33]
`模拟器上显示没有问题`
![](https://github.com/TopGuo/Flutter_MyApp/blob/master/doc/bugimage/1.png?raw=true)

`真机Android上显示`
- 
![](https://github.com/TopGuo/Flutter_MyApp/blob/master/doc/bugimage/2.jpg?raw=true)
- 
![](https://github.com/TopGuo/Flutter_MyApp/blob/master/doc/bugimage/3.jpg?raw=true)
- 
![](https://github.com/TopGuo/Flutter_MyApp/blob/master/doc/bugimage/4.jpg?raw=true)

**Comment by duminos** [comment]
I have the same problem! please help!

**Comment by TopGuo** [comment]
> @TopGuo @duminos what is the android version on which you are testing

I use MI8 
![xiao mi](https://github.com/TopGuo/flutter_boss_v1.0/blob/master/bossapp/doc/shothot/Screenshot_2018-12-10-16-28-08-659_com.android.se.png?raw=true)

**Comment by hong6234** [comment]
android pie on emulator have the same problem

**Comment by TopGuo** [comment]
Oh, hope debug...

**Comment by baowonton** [comment]
> 
> 
> I have the same problem! please help!

 I have the same problem too, after I try to change border-radius.

Nexus 5X 27API, Android 8.1,  flutter 0.10.3-pre.142  ,fluttertoast-2.1.5


![screenshot_1544945309](https://user-images.githubusercontent.com/20221197/50051158-56f9df00-0148-11e9-9690-588c4b1fe09e.png)

**Comment by PonnamKarthik** [comment]
fixed in `v2.2.0`
