### ISSUE TITLE
Stuck with  Showing Recent Issues Undefined symbol: _OBJC_CLASS_$_CSToastStyle, _CSToastPositionTop, _CSToastPositionCenter, _CSToastPositionBottom

### ISSUE THREAD

**Issue by thenishchalraj** [ponnamkarthik/FlutterToast#332]
<img width="341" alt="Screenshot 2021-08-08 at 10 35 24 PM" src="https://user-images.githubusercontent.com/15857220/128639744-1545636a-ddb9-40b0-8f77-57fd51620879.png">
This is irritating me for last few hours. Not working in Xcode. Do you have any idea @ponnamkarthik ?

It will be a great help if you can do something. I am really stuck with the release because of this.

**Comment by thenishchalraj** [comment]
I removed this library from my flutter project and put a text with changing text and colours according to the response to show the user of the status. When I will have the time I will come back and resolve this issue with the library.

**Comment by WingCH** [comment]
this solution work form me

https://milanpanchal24.medium.com/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios-file-for-8c0cc28ec832

podfile
```
...
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
#  add this-------
	  target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
		  config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
#  ---------

  end
end
```

**Comment by thenishchalraj** [comment]
This stopped the build to run form android studio for opened iPhone simulator, but from Xcode it's working fine. Any idea?
And thanks for the help @WingCH

**Comment by WingCH** [comment]
i can both run in Android Studio and Xcode

Have you tried `flutter clean` before run?
