### ISSUE TITLE
Give support for other platforms also like windows, macos, linux.

### ISSUE THREAD

**Issue by dnsoumik** [ponnamkarthik/FlutterToast#336]

**Comment by ponnamkarthik** [comment]
This plugin has two different kind of toasts one with the context other without context 

https://github.com/ponnamkarthik/FlutterToast#toast-with-buildcontext-all-platforms

check above link for more details

**Comment by dnsoumik** [comment]
![screenshot-pub dev-2021 08 29-00_37_13](https://user-images.githubusercontent.com/30685539/131228319-3da04ad6-a410-4e99-a8bf-cd7899833c0e.png)

Then @ponnamkarthik  why is still saying android, ios, web support only?
