### ISSUE TITLE
Why it is showing only support for Android, IOS, Web

### ISSUE THREAD

**Issue by dnsoumik** [ponnamkarthik/FlutterToast#339]
![screenshot-pub dev-2021 08 29-00_37_13](https://user-images.githubusercontent.com/30685539/131228319-3da04ad6-a410-4e99-a8bf-cd7899833c0e.png)

**Comment by Muthes** [comment]
These Repo supports only Android , ios and web

**Comment by ponnamkarthik** [comment]
Yes actually this project has both package and a plugin, Initially it was released as a plugin which supports only android, ios and web but later extended it as a package to support all platforms
