### ISSUE TITLE
Flutter toast background color

### ISSUE THREAD

**Issue by Pandi17** [ponnamkarthik/FlutterToast#340]
Flutter toast background colour is not working  in android 11 but working in android 10 my flutter sdk 2.2.3, please fix as soon as possible

 fluttertoast: ^8.0.8

**Comment by Pandi17** [comment]
Sorry, accidently closed this issue, issue still remains

**Comment by RTRenjith** [comment]
same issue for me too, any update?

**Comment by Pandi17** [comment]
> same issue for me too, any update?

Not yet bro

**Comment by yaochangliang159** [comment]
the same to me

**Comment by shadabunique** [comment]
@Pandi17  Trying to reproduce on Android 11 but it works for me. 
I tried -

       Fluttertoast.showToast(
        msg: "Toast with red background",
        toastLength: Toast.LENGTH_SHORT,
        backgroundColor: Colors.red,
        textColor: Colors.white);

And I can see a toast with red background and  white text.
Can you post the code you are trying on your end?

**Comment by RTRenjith** [comment]
I'm using pixel 3a API 30 x86 Android emulator

```
Fluttertoast.showToast(
                        msg: "Logged out!",
                        toastLength: Toast.LENGTH_LONG,
                        gravity: ToastGravity.SNACKBAR,
                        backgroundColor: Colors.red,
                        textColor: Colors.white,
                        fontSize: 16.0
                    );
```
doesn't workl :
![Screenshot_1633318438](https://user-images.githubusercontent.com/69429234/135789151-a5ae6f99-955a-4a9e-b964-4e4feb9daaed.png)
(

**Comment by Pandi17** [comment]
> @Pandi17 Trying to reproduce on Android 11 but it works for me. I tried -
> 
> ```
>    Fluttertoast.showToast(
>     msg: "Toast with red background",
>     toastLength: Toast.LENGTH_SHORT,
>     backgroundColor: Colors.red,
>     textColor: Colors.white);
> ```
> 
> And I can see a toast with red background and white text. Can you post the code you are trying on your end?

Same code only I'm using, but not working in android 11 but working in android 10, both in emulator and in real device

**Comment by xahid71** [comment]
Same problem, My Code scenario - 

```
class ToastMessage {
  static void error(String message) {
    Fluttertoast.showToast(
      msg: message,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.BOTTOM,
      timeInSecForIosWeb: 1,
      backgroundColor: Colors.red,
      textColor: Colors.white,
      fontSize: 16.0,
    );
  }

  static void success(String message) {
    Fluttertoast.showToast(
      msg: message,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.BOTTOM,
      timeInSecForIosWeb: 1,
      backgroundColor: Colors.green,
      textColor: Colors.white,
      fontSize: 16.0,
    );
  }
}
```

Red Color  and green color are not working in my case!

**Comment by DavideM12** [comment]
Same issue for me. Background color doesn't work on Android 11

**Comment by DavideM12** [comment]
I downloaded the whole repository with the last commit of C4st3ll4n and now it works!
The author of this packages should publish the new version on pub.dev

**Comment by mikekosulin** [comment]
Confirmed.
Pixel 3, Android 12.

**Comment by DOCSPLOIT** [comment]
if you're using a `Color(<your_color>)` which does not seems to work me, you have to create a color_swatch with ```MaterialColor```

**Comment by alarmatwork** [comment]
Android 12 will show their colour and also app icon
![Screenshot_20220128-152724](https://user-images.githubusercontent.com/2363137/151555049-85e16dd8-32c3-403c-8342-9de9ba649688.jpg)
n

**Comment by himanshupapreja** [comment]
> Android 12 will show their colour (probably matches with dark background color of OS) and also app icon ![Screenshot_20220128-152724](https://user-images.githubusercontent.com/2363137/151555049-85e16dd8-32c3-403c-8342-9de9ba649688.jpg) n

I am facing the same problem. getting icon and black background but my color is not displaying
