### ISSUE TITLE
Unable to work and how to set border radius in this toast?

### ISSUE THREAD

**Issue by Govindbetterlives** [ponnamkarthik/FlutterToast#341]
Fluttertoast.showToast(
        msg: "This is Center Short Toast",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
        timeInSecForIosWeb: 1,
        backgroundColor: Colors.red,
        textColor: Colors.white,
        fontSize: 16.0
    );

**Comment by ponnamkarthik** [comment]
Platform support is limited not able to add border radius
