### ISSUE TITLE
 Showing Recent Issues Undefined symbol: _OBJC_CLASS_$_CSToastStyle, _CSToastPositionTop,  _CSToastPositionCenter,  _CSToastPositionBottom

### ISSUE THREAD

**Issue by ketancts** [ponnamkarthik/FlutterToast#344]
![Screenshot 2021-09-17 at 4 38 17 PM](https://user-images.githubusercontent.com/78349298/133773072-106e89e1-b68f-4424-acb7-0eb621eb3b76.png)

Showing Recent Issues
Ignoring file /Users/PC_NAME/Library/Developer/Xcode/DerivedData/Runner-cpxskaptiwqqsoayonwwjwypkdas/Build/Products/Debug-iphonesimulator/Toast/Toast.framework/Toast, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64

**Comment by melikhanHosdogdu** [comment]
Yeah, I have been faced same problem, is there any solution?
