### ISSUE TITLE
Execution failed for task ':fluttertoast:compileDebugKotlin'.

### ISSUE THREAD

**Issue by CyberSwatTeam990000** [ponnamkarthik/FlutterToast#345]
I get a similar problem to these guys 
https://stackoverflow.com/questions/65378815/ponnamkarthik-toast-fluttertoast-methodcallhandlerimpl-kt-when-compile-flutter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I guess I won't be using this library anymore

**Comment by Muthes** [comment]
execute " flutter clean " in your terminal and pub get and pub upgrade then run your project , i had too this issues in my project after i run this procedure it clears...
