### ISSUE TITLE
obscureText

### ISSUE THREAD

**Issue by nanhai-13** [ponnamkarthik/FlutterToast#350]
while focus on TextField Widget (property  obscureText=true, i.e. password input field)
pop toast msg is blocked by input area of keyboard

**Comment by BREEZE1987** [comment]
I also encountered the same problem, using Huawei mobile phones

**Comment by zwind007** [comment]
> I also encountered the same problem, using Huawei mobile phones

Is it solved? The same issue. Huawei Mate30 Pro.
