### ISSUE TITLE
Flutter toast gravity - ios

### ISSUE THREAD

**Issue by InspectlyMads** [ponnamkarthik/FlutterToast#354]
Gravity does not seem to work on iOS. The toast is always shown in the bottom of the screen. On my android it works perfectly fine. Same goes for the backgroundColor. It is always shown as a transparent black on iOS.

` Fluttertoast.showToast(
          msg: "Hello there..",
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.TOP,
          timeInSecForIosWeb: 1,
          backgroundColor: CustomTheme.transparentBlack,
          textColor: Colors.white,
          fontSize: 16.0);`

**Comment by Samkit02** [comment]
in my case it is opposite in ios toast is coming at center and in android the toast is shown default gravity i.e bottom only

please solve this issue

**Comment by pictureframing** [comment]
Same for me on Android

**Comment by ponnamkarthik** [comment]
Platform support for android is limited
