### ISSUE TITLE
Fluttertoast.showToast() Stop Working Recently

### ISSUE THREAD

**Issue by mingzew** [ponnamkarthik/FlutterToast#361]
Platform: 
Android 10

Hi I have the following piece of code:

```
Future<bool?> showFlutterToast(String msg, {int? timeShown}) {
  return Fluttertoast.showToast(
      msg: msg,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.BOTTOM,
      timeInSecForIosWeb: timeShown ?? 4,
      backgroundColor: white,
      textColor: black,
      fontSize: 14.0
  );
}
```

Whenever I need to call this, I just call it like 
```
          showFlutterToast("toast here");
```

However this stopped working in the past 24 hours. I thought this may have something to do with cache, so I did 
```
flutter clean
```
but it didn't help. Please let me know if there are other tricks I can try to get this working.

**Comment by qwea363636** [comment]
same issue here

**Comment by ponnamkarthik** [comment]
Need More info
