### ISSUE TITLE
Can't run in ios , Build Failed , Module 'fluttertoast' not found

### ISSUE THREAD

**Issue by angelaeddie** [ponnamkarthik/FlutterToast#366]
-> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`

     Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`

    Resolving dependencies of `Podfile`

**Comment by diogo10** [comment]
Same here

**Comment by arslankaleem7229** [comment]
delete following files and folders

```
1).  ios/symlinks
2). Pods
3). Podfile.lock
```

and after that run following command in terminal

```
cd ios && pod deintegrate && pod install
```

this helped me

**Comment by xni06** [comment]
Doesn't work for me - I'm on an M1

**Comment by AbbosSaidov** [comment]
8.0.8 works

**Comment by alexpriceuk** [comment]
I also get this issue for simulators on apple M1 chip

**Comment by sisithaJWA** [comment]
open the project Runner.xcworkspace file instead of Runner.xcodeproj.
