### ISSUE TITLE
Long message with multi line message not showing in proper way.

### ISSUE THREAD

**Issue by TheDev563** [ponnamkarthik/FlutterToast#367]
How to show completed long message without and text crop?

<img width="312" alt="Screenshot 2022-01-19 at 8 22 29 PM" src="https://user-images.githubusercontent.com/67050093/150155179-6720b53f-2945-459e-9efa-6e9931ba735a.png">

**Comment by Kishan-Somaiya** [comment]
did you ever find the solution? @TheDev563

**Comment by Subhangi3** [comment]
@TheDev563 and @Kishan-Somaiya Did u find any solution to this?

**Comment by ponnamkarthik** [comment]
Please use Toast with context

Platform is truncating the text
