### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by arslankaleem7229** [ponnamkarthik/FlutterToast#368]
When I use `GlobalContextKey` which is basically a `globalNavigatorKey` linked to `MaterialApp` parameter `navigatorkey`. But everywhere else I am using this key its working except this and I am getting following error:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      FToast._showOverlay
package:fluttertoast/fluttertoast.dart:148
#1      FToast.showToast
package:fluttertoast/fluttertoast.dart:214
```

I am calling `fToast.showToast` and before calling this I have checked the context by printing the statement `fToast.context != null` which is returning `true`

**Comment by ponnamkarthik** [comment]
please check you code have you called init the FToast

```
    fToast = FToast();
    fToast.init(context);
```
