### ISSUE TITLE
Doesn't work after await code or Future.then

### ISSUE THREAD

**Issue by z234009184** [ponnamkarthik/FlutterToast#37]
```
Response res = await Dio().post(BASEURL + submitFeedbackUrl, data: params);
    Fluttertoast.showToast(
      msg: 'Success',
      timeInSecForIos: 2,
      gravity: ToastGravity.CENTER,
    );
```

doesn't work!

**Comment by PonnamKarthik** [comment]
it needs to wait until the `await` is completed

please check by adding a print statement between await and showing Toast

**Comment by z234009184** [comment]
It still not work for me after  await already complete

**Comment by PonnamKarthik** [comment]
have you added a print statement between await and Toast

please check whether the statement is printed
