### ISSUE TITLE
Execution failed for task ':fluttertoast:compileDebugKotlin' after upgrading to Flutter 2.10.1

### ISSUE THREAD

**Issue by ajhwb** [ponnamkarthik/FlutterToast#372]
Having this issue after upgrading to Flutter 2.10.1
There are workarounds i have tried including flutter clean and rebuild, but seem didn't solve my case.

`fluttertoast: ^8.0.8`

Error messages:

```
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s

┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                       │
│ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then │
│ update C:\Projects\kjb\android\build.gradle:                                                 │
│ ext.kotlin_version = '<latest-version>'                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
```

Flutter version:

```
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (6 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by Danish-Git** [comment]
Hi,
I am also getting same issue

**Comment by diazsasak** [comment]
Hi, 
I am also getting the same issue

**Comment by chandragupt1201** [comment]
same issue for me also.

**Comment by doch2** [comment]
There is a code in the #370 pull request that can solve this issue.
If that Branch becomes Merge, we can solve this problem.

**Comment by ajhwb** [comment]
> There is a code in the #370 pull request that can solve this issue. If that Branch becomes Merge, we can solve this problem.

Yes, I have tried this and it worked

What I did are:

1. Manually adding `ext.kotlin_version = '1.6.10'` in fluttertoast `android\build.gradle`

```
group 'com.example.FlutterToast'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        jcenter()
    }
...
```

2. Changing gradle `distributionUrl` in `android\gradle\wrapper\gradle-wrapper.properties` from gradle-5.6.2-all.zip to gradle-6.1.1-all.zip
```
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```
As it generated error like `The current Gradle version 5.6.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.1.1 or newer, or the previous version of the Kotlin plugin` in my case.

**Comment by red282** [comment]
#370 now merged 🎉
