### ISSUE TITLE
Incompatible classes were found in dependencies.

### ISSUE THREAD

**Issue by abhihasabe** [ponnamkarthik/FlutterToast#374]
Getting error in latest version
Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/0464082e81de712709b8918eac577657/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/2964b3bd074cce42cde0bddbdb8bb158/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (15, 6): Class 'kotlin.jvm.JvmStatic' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/jvm/JvmStatic.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (18, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (23, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (27, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (31, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (33, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (37, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt: (38, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (19, 15): Unresolved reference: Exception
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (26, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (49, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (52, 26): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (60, 42): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (62, 26): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (64, 30): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (67, 30): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (69, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (70, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (71, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (73, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (78, 42): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (81, 42): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (89, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (91, 36): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (94, 36): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (97, 36): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (102, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (103, 43): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (103, 66): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (105, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (107, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (109, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (112, 30): Unresolved reference: isInitialized
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (113, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (115, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (117, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (122, 22): Unresolved reference: isInitialized
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.9\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt: (127, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
The class is loaded from C:/Users/abhasabe/.gradle/caches/transforms-2/files-2.1/29b23ea272c7f8f6ce1a3b6be919bcda/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Shanoobmk** [comment]
what solved my problem is changing this at build.gradle

from

ext.kotlin_version = '1.3.50'
to

ext.kotlin_version = '1.6.0'
