### ISSUE TITLE
Unhandled Exception MissingPluginException

### ISSUE THREAD

**Issue by arcahyadi** [ponnamkarthik/FlutterToast#375]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:100:17)
<asynchronous suspension>

already rebuild apps
do flutter clean, flutter pub get

but still have the same problem

> void login() async {
    if (inputUsername.text.isEmpty || inputPass.text.isEmpty) {
      Fluttertoast.showToast(msg: 'Input tidak boleh kosong');
      return;
    }
    setState(() => isLoading = true);
    try {
      final authService = AuthService();
      final token = await authService.login(inputUsername.text, inputPass.text);
      SessionService.setSessionLogin();
      Fluttertoast.showToast(msg: 'berhasil');
      // Navigator.push(context, HomePage());

    } on DioError catch (e) {
      Fluttertoast.showToast(msg: e.response?.data['message']);
    } catch (e) {
      Fluttertoast.showToast(msg: e.toString());
    }
    setState(() => isLoading = false);
  }

**Comment by arcahyadi** [comment]
![image](https://user-images.githubusercontent.com/76746019/156870508-8f0e27fa-b4c2-4d28-bbfc-c5f720f82a09.png)

**Comment by netgfx** [comment]
Why was this closed? I have the same issue. Was it patched or something wrong with he client code (although I just followed the ReadMe instructions)

**Comment by svonidze** [comment]
the issue still happens for me

@arcahyadi why have you closed this?

**Comment by svonidze** [comment]
the issue still happens for me on various Android devices on the version insatlled from the Store, not on emulators.
@arcahyadi why have you closed this?

re
https://github.com/ponnamkarthik/FlutterToast/issues/198
https://github.com/ponnamkarthik/FlutterToast/issues/375
https://github.com/ponnamkarthik/FlutterToast/issues/97
