### ISSUE TITLE
Stack incoming toasts?

### ISSUE THREAD

**Issue by bobwiller** [ponnamkarthik/FlutterToast#377]
Couple quick questions:
If I need my user to dismiss a toast, is there a way to do that without using a long toastDuration? (Right now I wrap my toast Container in an InkWell, and use onTap: () => removeCustomToast()  and set the duration to an hour).

Because I need my users to acknowledge the toast messages, is there a way to stack them as they come in, so they can choose which ones to dismiss? (e.g. if they want to dismiss them in a different order in which they came in)

Thanks,
Bob

**Comment by ponnamkarthik** [comment]
No as of now all the toasts are queued and it appears one after the other
