### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by iqfareez** [ponnamkarthik/FlutterToast#378]
Error when try to show toast on Windows

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
<asynchronous suspension>
#1      Fluttertoast.showToast
package:fluttertoast/fluttertoast.dart:100
<asynchronous suspension>
```

Perhaps can use the web styling.

**Comment by dbsxdbsx** [comment]
I got same issue.

**Comment by iqfareez** [comment]
Need to the BuildContext method to be able to target all platforms. 

https://pub.dev/packages/fluttertoast#toast-with-buildcontext-all-platforms

**Comment by dbsxdbsx** [comment]
> Need to the BuildContext method to be able to target all platforms.
> 
> https://pub.dev/packages/fluttertoast#toast-with-buildcontext-all-platforms

I also got this doc, but the document is not quite readable. I am go on to  switch to other package.

**Comment by geboct** [comment]
> > Need to the BuildContext method to be able to target all platforms.
> > https://pub.dev/packages/fluttertoast#toast-with-buildcontext-all-platforms
> 
> I also got this doc, but the document is not quite readable. I am going on to switch to other packages.

Did u get any

**Comment by dbsxdbsx** [comment]
> > > Need to the BuildContext method to be able to target all platforms.
> > > https://pub.dev/packages/fluttertoast#toast-with-buildcontext-all-platforms
> > 
> > 
> > I also got this doc, but the document is not quite readable. I am going on to switch to other packages.
> 
> Did u get any

What do you mean?
