### ISSUE TITLE
Fluttertoast.showToast, how can I increase toastLength for ios devices

### ISSUE THREAD

**Issue by parteekpassi** [ponnamkarthik/FlutterToast#384]
I am using if for ios and set toastLength attribute value to Toast.LENGTH_LONG , but it doesn't stay long, it goes away after 
 couple of seconds.
Is that possible that we can set up the length in seconds whatever we want, instead of using enums ?

**Comment by alexlozdev** [comment]
Fluttertoast.showToast(
      msg: msg,
      toastLength: lengthLong ? Toast.LENGTH_LONG : Toast.LENGTH_SHORT, // this is only for Android
      timeInSecForIosWeb: 5, // please set the show time here for iOS and web
  );

**Comment by ponnamkarthik** [comment]
Platform Support is limited if you want to use Toast without context
