### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by osamamohammed98** [ponnamkarthik/FlutterToast#386]
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set
    to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'Toast' from project 'Pods')

**Comment by ArunJRK** [comment]
Modify your install section in pod file to config like below
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
    end
  end
end
```4
