### ISSUE TITLE
fluttertoast causing iOS simulator scroll too fast on Apple Silicon processors

### ISSUE THREAD

**Issue by Stardusted1** [ponnamkarthik/FlutterToast#388]
Steps to reproduce: 
1. Add `fluttertoast: ^8.0.9` to your pubspec 
2. Run `flutter pub get `
3. Run your app in debug mode in iOS Simulator

Now every list with BouncingScrollPhysics will get super scroll force.

I found two solutions: 
- Remove fluttertoast from pubspec  
- Run simulator under Rosetta 

Used Apple Mac M1 and iOS 15.4 simulators

<details>

  <summary>Flutter doctor</summary>

  [✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-arm, locale ru-UA)
  [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
  [✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
  [✓] Chrome - develop for the web
  [✓] Android Studio
  [✓] VS Code (version 1.66.2)
</details>

**Comment by ariefwijaya** [comment]
any update on this?

**Comment by dg76** [comment]
I think I have found a fix for it. I have created a pull request for the fix. :-)
