### ISSUE TITLE
Xcode Parse Error:fatal error: module 'fluttertoast' not found

### ISSUE THREAD

**Issue by harmispatel** [ponnamkarthik/FlutterToast#395]
When I upgrade flutter tost from 8.0.8 to 8.0.9 I am getting this error when I try to Install application first time on simulator after deleting .symblinks,pods,podlock all this file

https://github.com/ponnamkarthik/FlutterToast/issues/314

Please check more

**Comment by SuryaSharpsell** [comment]
Facing the same issue - `Parse Issue (Xcode): Module 'fluttertoast' not found`

**Comment by nitish-nanda** [comment]
I'm also facing the same issue in the ios build `fluttertoast module not found`

**Comment by MukhametzhanDev** [comment]
+1

**Comment by lonelyWalkor** [comment]
+1

**Comment by rizkiiansyah** [comment]
+1

**Comment by BaoDat** [comment]
+1

**Comment by wkl007** [comment]
+1

**Comment by hoangmanhh99** [comment]
You can pod install (in ios folder) and run again. I solved this issue.

**Comment by adrianofreires** [comment]
> You can pod install (in ios folder) and run again. I solved this issue.

for me appears a error when run pod install

**Comment by hoangmanhh99** [comment]
> > You can pod install (in ios folder) and run again. I solved this issue.
> 
> for me appears a error when run pod install

what error? Can you post image?

**Comment by adrianofreires** [comment]
I managed to get the pod to work, but even doing what you are suggesting I still have the same error, either with version 8.0.8 or version 8.0.9.
I've already done the flutter clean command, deleted the podfile and podfile.lock files, even deleted the Pods folder and run the flutter pub get command, but the error in the image remains
<img width="473" alt="Captura de Tela 2022-08-23 às 20 02 44" src="https://user-images.githubusercontent.com/38692077/186281378-3aec3a30-ff12-4f94-b6f7-2366882c5f96.png">
.

**Comment by hoangmanhh99** [comment]
@adrianofreires Do you setup ios 12.0 on Xcode?

**Comment by adrianofreires** [comment]
> 

I had not! Thanks! now works halfway but it's a problem in Firebase!

**Comment by yoer** [comment]
为什么要设置这么高的平台，flutter这么多库里面，你们是唯一打包会碰到问题的

**Comment by karamatpkid** [comment]
Facing this issue , 
Tried Steps
1.
 Platform IOS 14
 IPHONEOS_DEPLOYMENT_TARGET 
2. Pod update,install
3. clean ios build folder
 
Parse Issue (Xcode): Module 'fluttertoast' not found
backgroundremover/ios/Runner/GeneratedPluginRegistrant.m:29:8
