### ISSUE TITLE
how to change font of toast?

### ISSUE THREAD

**Issue by Esniper90** [ponnamkarthik/FlutterToast#40]
Is there any way to change the font of toast? i changed the whole app font trough pubspec.yaml but not work in toast

**Comment by PonnamKarthik** [comment]
flutter/flutter#25690

**Comment by wuestkamp** [comment]
I would also like to change the font, maybe even be able to pass a custom Text widget?

**Comment by easazade** [comment]
common this is important why can't we change the font?

**Comment by nt4f04uNd** [comment]
what's the reason this is closed?

**Comment by nt4f04uNd** [comment]
fyi i patched your plugin for myself, feel free to use it https://github.com/nt4f04uNd/FlutterToast/commits/patch

**Comment by ponnamkarthik** [comment]
@nt4f04uNd Can you do a PR

**Comment by nt4f04uNd** [comment]
it's android-only but it should be similarly pretty straght-forward to implement this on other platforms. i do not have much time right now to add it to other platforms
