### ISSUE TITLE
Toast background color is not changing in Android 12 or Upper.

### ISSUE THREAD

**Issue by himanshupapreja** [ponnamkarthik/FlutterToast#413]
Toast background color is not changing in Android 12 or Upper.

This is my code

Fluttertoast.showToast(
        msg: msg,
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.BOTTOM,
        backgroundColor: isError ? const Color.fromRGBO(139, 0, 0, 1) : const Color.fromRGBO(0, 100, 0, 1),
        textColor: Colors.white
    );
![WhatsApp Image 2023-01-26 at 23 34 44](https://user-images.githubusercontent.com/52091189/214914745-d55567de-4ade-4226-a1d2-f1eca1f94831.jpg)

**Comment by bashiransari** [comment]
Having the same issue here

**Comment by LibraZhu** [comment]
Having the same issue here

**Comment by jwseph** [comment]
Having the same issue here

**Comment by ponnamkarthik** [comment]
https://github.com/ponnamkarthik/FlutterToast#note-android

as of android 12  default toast has major changes which no longer supports the view customization
