### ISSUE TITLE
Version 8.1.3 giving a build error

### ISSUE THREAD

**Issue by Rqmco** [ponnamkarthik/FlutterToast#416]
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28: Error: Member not found: 'Overlay.maybeOf'.
    var _overlay = Overlay.maybeOf(context!);
                           ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context?.mounted != true) {
                 ^^^^^^^

To fix this issue temporarely change the dependency to 'fluttertoast: 8.1.2' till its fixed

**Comment by ponnamkarthik** [comment]
which version of flutter are you using

**Comment by Rqmco** [comment]
Version 3.3.10

**Comment by Wouter12** [comment]
same issue here on flutter 3.3.9

**Comment by Wouter12** [comment]
seems to be an issue with breaking changes in flutter 3.7.0 
https://github.com/flutter/flutter/issues/119499
https://github.com/flutter/website/pull/8188 

I would suggest retracting this version, and publishing it as a minor version with a min flutter SDK constraint of `>=3.7.0`

**Comment by wangxiongtao** [comment]
occurred the same error in version 
 flutter_windows_2.10.1-stable

**Comment by wangxiongtao** [comment]
and  Version 8.0.8

**Comment by ManoharSQ** [comment]
same issue here for flutter 3.3.10

**Comment by Imesh7** [comment]
> same issue here for flutter 3.3.10

@ManoharSQ  have you found any solution?

**Comment by ManoharSQ** [comment]
@Imesh7 downgrade like fluttertoast: 8.1.2 
And working fine

**Comment by Imesh7** [comment]
> 



> @Imesh7 downgrade like fluttertoast: 8.1.2 And working fine

Thank you , its works

**Comment by GjoAbrahamN** [comment]
it's not working using  fluttertoast: 8.1.2

**Comment by chirag-dt** [comment]
same issue here, not working

**Comment by chirag-dt** [comment]
upgrade flutter version 3.7.2 and use latest fluttertoast version. it will work.   @GjoAbrahamN working fine now

**Comment by Imesh7** [comment]
> it's not working using fluttertoast: 8.1.2

working with flutter 3.7.1 & fluttertoast 8.1.3

**Comment by alloza95** [comment]
Same issue with `flutter 3.6.0` & `fluttertoast: ^8.0.7`

**Comment by bilalalmofleh** [comment]
Same issue with Flutter (Channel stable, 3.3.10)

**Comment by yaotiancheng-ola** [comment]
Same issue with Flutter (Channel stable, 3.3.4)

**Comment by GjoAbrahamN** [comment]
Yes it is working with` flutter 3.7.2` and `fluttertoast: ^8.0.7`

**Comment by rickypid** [comment]
same issue here on flutter 3.3.10

**Comment by balaji101010** [comment]
fluttertoast: 8.0.7 without the  `^`
works with flutter 3.3.10

**Comment by balaji101010** [comment]
fluttertoast: 8.0.7 without the `^` worked for me with flutter 3.3.10
  and a macos restart

**Comment by herbcookey** [comment]
same issue with flutter 3.3.7 and fluttertoast^8.1.3

**Comment by wangxiongtao** [comment]
> fluttertoast: 8.0.7 without the `^` worked for me with flutter 3.3.10 and a macos restart

thanks , I  also working fine   fluttertoast: 8.0.8 without the `^`

**Comment by xieenming** [comment]
Same error with Flutter 3.0.5 and fluttertoast 8.1.3

```
/opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28: Error: Member not found: 'Overlay.maybeOf'.
    var _overlay = Overlay.maybeOf(context!);
                           ^^^^^^^
                           
/opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/hostedtoolcache/flutter/stable-3.0.5-x64/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context?.mounted != true) {
                 ^^^^^^^
```

**Comment by wangxiongtao** [comment]
> downgrade like fluttertoast: 8.1.2 without the ^
> And working fine

**Comment by wangxiongtao** [comment]
> Same error with Flutter 3.0.5 and fluttertoast 8.1.3
> 
> ```
> /opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28: Error: Member not found: 'Overlay.maybeOf'.
>     var _overlay = Overlay.maybeOf(context!);
>                            ^^^^^^^
>                            
> /opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/hostedtoolcache/flutter/stable-3.0.5-x64/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
>     if (context?.mounted != true) {
>                  ^^^^^^^
> ```

downgrade like fluttertoast: 8.1.2 without the ^
And working fine

**Comment by xieenming** [comment]
> To fix this issue temporarely change the dependency to 'fluttertoast: 8.1.2' till its fixed



> > Same error with Flutter 3.0.5 and fluttertoast 8.1.3
> > ```
> > /opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28: Error: Member not found: 'Overlay.maybeOf'.
> >     var _overlay = Overlay.maybeOf(context!);
> >                            ^^^^^^^
> >                            
> > /opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
> >  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/hostedtoolcache/flutter/stable-3.0.5-x64/packages/flutter/lib/src/widgets/framework.dart').
> > Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
> >     if (context?.mounted != true) {
> >                  ^^^^^^^
> > ```
> 
> downgrade like fluttertoast: 8.1.2 without the ^ And working fine

Ok，changed to ```fluttertoast: 8.1.2``` and it is ok. thanks

**Comment by Abu-muhab** [comment]
> &

worked for me. Thanks!

**Comment by irfan-ahmed-1982** [comment]
Yes 8.1.2 without^ is working for me too...

**Comment by iamtechmanish** [comment]
fluttertoast: 8.1.2 without ^ and flutter version 3.3.10 working fine with me.

**Comment by openstudio2022** [comment]
Same error with Flutter 3.0.0 and fluttertoast 8.1.3

**Comment by abdim-k** [comment]
same error here flutter toast build error how can i fix it

**Comment by Rqmco** [comment]
@abdim-k 
> To fix this issue temporarely change the dependency to 'fluttertoast: 8.1.2' till its fixed

**Comment by wangxiongtao** [comment]
> same error here flutter toast build error how can i fix it

downgrade like fluttertoast: 8.1.2 without the ^ And working fine

**Comment by drown0315** [comment]
```
fluttertoast: ">=8.1.2 <8.1.3"
```
that work for me

**Comment by ponnamkarthik** [comment]
please update to latest version `8.2.0` also check docs their is a change in the implementation for toast with context

```dart
MaterialApp(
    builder: FToastBuilder(),
    home: MyApp(),
    navigatorKey: navigatorKey,
),
```

**Comment by thirstyde** [comment]
Yes 8.1.2 without^ is working for me too
