### ISSUE TITLE
A fluttertoast error?

### ISSUE THREAD

**Issue by Tangzheng-Dev-GitHub** [ponnamkarthik/FlutterToast#417]
G:/flutter_windows_3.3.4-stable/flutter/.pub-cache/hosted/[pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28](http://pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28): Error: Member not found: 'Overlay.maybeOf'.
    var _overlay = Overlay.maybeOf(context!);
                           ^^^^^^^
/G:/flutter_windows_3.3.4-stable/flutter/.pub-cache/hosted/[pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18](http://pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18): Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/G:/flutter_windows_3.3.4-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
framework.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context?.mounted != true) {
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

# does anyone know what error is this
# it's going to kill me
# please tell me the answer

_this happened when I was debuging with a android device_

**Comment by Ali-Ussama** [comment]
it occurs with me too, this is a sick issue.

**Comment by umarabdul-malik** [comment]
@Tangzheng-Dev-GitHub adding this file to my pubspec.yaml file worked for me.
`dependency_overrides:
  fluttertoast: 8.1.2

`

**Comment by herbcookey** [comment]
Yes it also occured to me. I tried to clean pub cache and reinstall libraries again. But its error still exist.

**Comment by xieenming** [comment]
```
/opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:165:28: Error: Member not found: 'Overlay.maybeOf'.
    var _overlay = Overlay.maybeOf(context!);
                           ^^^^^^^
                           
/opt/hostedtoolcache/flutter/stable-3.0.5-x64/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.1.3/lib/fluttertoast.dart:154:18: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/hostedtoolcache/flutter/stable-3.0.5-x64/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context?.mounted != true) {
                 ^^^^^^^
```

In the version 8.1.3, also encounter this issue. when will it be fixed ?

**Comment by harmeet-sidhu** [comment]
Flutter toast `v8.1.3` cannot work with a Flutter version older than 3.7.0 because of a [breaking change](https://docs.flutter.dev/docs/release/breaking-changes/supplemental-maybeOf-migration) in `Flutter v3.7.0`. You have to either use `fluttertoast v8.1.2` or you have to upgrade your flutter version to `v3.7.0`+.

**Comment by xieenming** [comment]
> Flutter toast `v8.1.3` cannot work with a Flutter version older than 3.7.0 because of a [breaking change](https://docs.flutter.dev/docs/release/breaking-changes/supplemental-maybeOf-migration) in `Flutter v3.7.0`. You have to either use `fluttertoast v8.1.2` or you have to upgrade your flutter version to `v3.7.0`+. @Tangzheng-Dev-GitHub @Ali-Ussama @herbcookey @xieenming

Ok, thanks. Temporarely I change the dependency to 'fluttertoast: 8.1.2'

**Comment by harmeet-sidhu** [comment]
@ponnamkarthik Please update the readme file with breaking changes that should mention that this plugin cannot work with the Flutter versions older than v3.7.0.

**Comment by Tangzheng-Dev-GitHub** [comment]
no error anymore at `fluttertoast: ^8.0.8`

**Comment by herbcookey** [comment]
@xieenming thanks! I just downgraded my fluttertoast version to 8.1.2 temporately. 

And I think I'd better upgrade my flutter to upper than 3.7.0

**Comment by rafiullah445** [comment]
all of this can not working i have try

**Comment by harmeet-sidhu** [comment]
> all of this can not working i have try

@rafiullah445 what version of Flutter and Fluttertoast you are using and what is the error that you are getting??

**Comment by rafiullah445** [comment]
> > all of this can not working i have try
> 
> @rafiullah445 what version of Flutter and Fluttertoast you are using and what is the error that you are getting??

3.3.9

**Comment by FriendlyNeighbor** [comment]
even if you add dependency_overrides: fluttertoast: 8.1.2 to your pubspec it will still detect 8.1.3. even after multiple pub cache cleaning. what a frustrating update.

**Comment by AjilAshok** [comment]
Both is solution is not working for me anyother solution?

**Comment by AjilAshok** [comment]
Both solution is not working for me ..anyother solution?

**Comment by ponnamkarthik** [comment]
sorry for the issue guys now the latest version will support old versions of the flutter remove the usage for `Overlay.maybeOf` 

please update to latest version `8.2.0` also check docs their is a change in the implementation for toast with context

```dart
MaterialApp(
    builder: FToastBuilder(),
    home: MyApp(),
    navigatorKey: navigatorKey,
),
```
