### ISSUE TITLE
How to destroy the toast ?

### ISSUE THREAD

**Issue by qazse1234567** [PonnamKarthik/FlutterToast#42]

**Comment by PonnamKarthik** [comment]
No way to destroy it manually

**Comment by MatthiasGehrmann** [comment]
first of all thank you for your great work on this.

may i ask, do you have any plans to implement that functionality in the near future ?
it would be great to have a feature to destroy / dismiss the toast !
:)

**Comment by PonnamKarthik** [comment]
Please check `2.2.8` version you can cancel the toasts

`Fluttertoast.cancel()`
