### ISSUE TITLE
Member not found: 'Overlay.maybeOf'.

### ISSUE THREAD

**Issue by Nachi-on-git** [ponnamkarthik/FlutterToast#420]
Getting the error while I am on latest version i.e, 8.1.3.
                                       ^
: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
date_picker.dart:7665
- 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../development/flutter/packages/flutter/lib/src/rendering/viewport.dart').
viewport.dart:1
  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);
  FAILURE: Build failed with an exception.

* Where:
Script '/Users/nachilabade/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/nachilabade/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by thirstyde** [comment]
> Getting the error while I am on latest version i.e, 8.1.3. ^ : Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't. date_picker.dart:7665
> 
> * 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../development/flutter/packages/flutter/lib/src/rendering/viewport.dart').
>   viewport.dart:1
>   RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);
>   FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/Users/nachilabade/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command '/Users/nachilabade/development/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s

same problem

**Comment by ponnamkarthik** [comment]
please update to latest version `8.2.0` also check docs their is a change in the implementation for toast with context

```dart
MaterialApp(
    builder: FToastBuilder(),
    home: MyApp(),
    navigatorKey: navigatorKey,
),
```
