### ISSUE TITLE
v8.2.0 is still not compatible with Flutter <3.7

### ISSUE THREAD

**Issue by franzlst** [ponnamkarthik/FlutterToast#423]
Flutter checks if the context is mounted. [The way it does so](https://github.com/ponnamkarthik/FlutterToast/blob/master/lib/fluttertoast.dart#L154) is not compatible with Flutter <3.7. So it is still not possible to use FlutterToast > 8.1.2 with Flutter <3.7.

**Comment by ponnamkarthik** [comment]
fixed in `fluttertoast: ^8.2.1`

**Comment by franzlst** [comment]
Thank you for that quick fix 👍
