### ISSUE TITLE
Android 13 Toast withOut Build Context doesn't work properly

### ISSUE THREAD

**Issue by saracol** [ponnamkarthik/FlutterToast#433]
I have the last libraries
![imagen](https://user-images.githubusercontent.com/76536497/229767471-8d37536d-89c6-4e28-8184-0126b0220a0c.png)

I using Toast with No Build Context (Android & iOS) but the result in Android 11 and 13 is different
![imagen](https://user-images.githubusercontent.com/76536497/229771665-7d1d0e5c-341d-4747-a315-8c3a17b7200b.png)

`  Future<bool> _isAllConfigured() async {
    if(_newAlert == true) {
      _newAlert = false;
      return true;
    } else {
      bool notificationsAllowed = await configProvider.notificationsAllowed();
      bool notificationsSilenced = await configProvider.isNotificationSilenced();
      bool mediaSilenced = await configProvider.isMediaSilenced();
      bool hasNetworkConnectivity = await configProvider.hasNetworkConnectivity();
      if(!notificationsAllowed || notificationsSilenced || mediaSilenced || !hasNetworkConnectivity) {
        _currentTabIndex = 2;
        Fluttertoast.showToast(
            msg: "This is Center Short Toast " + "\n" + "This is Center Short Toast " + "\n" + "This is Center Short Toast " + "\n" + "This is Center Short Toast " + "\n" + "This is Center Short Toast " ,
            toastLength: Toast.LENGTH_SHORT,
            gravity: ToastGravity.CENTER,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.red,
            textColor: Colors.white,
            fontSize: 16.0
        );

        return false;
      } else {
        _currentTabIndex = _navigatingTo;
        return true;
      }

    }
  }`

**Comment by ponnamkarthik** [comment]
If API is greater than 31 then only MSG and Toast Length is considered remaining all fields are ignored as Android system removed the support to set Custom View for toast
