### ISSUE TITLE
Flutter web TypeError

### ISSUE THREAD

**Issue by mhbdev** [ponnamkarthik/FlutterToast#438]
I am using the latest version of fluttertoast. Using flutter version 3.10.0 stable channel and getting the error below:

```console
TypeError: Cannot read properties of null (reading 'exports')
assets/packages/fluttertoast/assets/toastify.js 14:48  <fn>
assets/packages/fluttertoast/assets/toastify.js 14:90  <fn>
```

**Comment by Mmisiek** [comment]
I have exactly the same error after the latest Flutter update. No idea why.

**Comment by DanilKarasev** [comment]
Same here

![Screenshot from 2023-05-16 01-48-50](https://github.com/ponnamkarthik/FlutterToast/assets/88264176/7f11561b-b7ef-4e70-bf29-b7b534b0eddd)

**Comment by OspreyRen** [comment]
Same here, and no toast showing

**Comment by VIP-Dev-Invisible** [comment]
is the issue solved ?

**Comment by Mmisiek** [comment]
> is the issue solved ?

It is.

**Comment by shivbo96** [comment]
@VIP-Dev-Invisible  yes it is resolved
