### ISSUE TITLE
xcode14 bulid error 

### ISSUE THREAD

**Issue by lockead** [ponnamkarthik/FlutterToast#463]
![Screenshot_1](https://github.com/ponnamkarthik/FlutterToast/assets/20179040/55265782-2626-48a7-a224-d79c6c8fef6c)
![Screenshot_2](https://github.com/ponnamkarthik/FlutterToast/assets/20179040/90a99ff3-d918-436b-bd9d-440f5f5bfc41)
Failed to build iOS app
User-Defined Issue (Xcode): Unsupported architecture
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/cdefs.h:900:1

User-Defined Issue (Xcode): Architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/machine/_types.h:33:1

Semantic Issue (Xcode): Unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:54:8

Semantic Issue (Xcode): Unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:55:8

Semantic Issue (Xcode): Unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:56:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:59:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:60:8

Semantic Issue (Xcode): Unknown type name '__uint64_t'; did you mean 'uint64_t'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:61:8

Semantic Issue (Xcode): Unknown type name '__darwin_natural_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:67:8

Semantic Issue (Xcode): Unknown type name '__uint16_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:69:8

Semantic Issue (Xcode): Unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:70:8

Semantic Issue (Xcode): Unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:71:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:72:8

Semantic Issue (Xcode): Unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:73:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:74:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types.h:75:8

User-Defined Issue (Xcode): Architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/machine/types.h:36:1

Semantic Issue (Xcode): Unknown type name '__darwin_intptr_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/_types/_intptr_t.h:31:8

Semantic Issue (Xcode): Unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/_types.h:42:8

Error (Xcode): too many errors emitted, stopping now

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:15:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/dispatch/dispatch.h:24:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/os/object.h:24:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/os/workgroup_base.h:7:9

Parse Issue (Xcode): Could not build module 'CoreFoundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:5:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/objc/NSObjCRuntime.h:7:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:26:9

Parse Issue (Xcode): Could not build module 'CoreFoundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:18:9

Parse Issue (Xcode): Could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:7:8

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:7:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:10:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:15:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:10:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceBase.h:11:9

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:7:8

Parse Issue (Xcode): Could not build module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:10:9

Parse Issue (Xcode): Could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:7:9

Parse Issue (Xcode): Could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:7:8

Parse Issue (Xcode): Could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/NSString+UserNotifications.h:7:8

Parse Issue (Xcode): Could not build module 'UIKit'
/Users/lockead/AndroidStudioProjects/com.xxx.app_dir/ios/Pods/Target%20Support%20Files/fluttertoast/fluttertoast-prefix.pch:1:8

Encountered error while building for device.
Process finished with exit code 1

**Comment by Hosamkawkgy** [comment]
Is there any update on this error? I am facing exactly the same error Are there any recommendations I would appreciate it?
