### ISSUE TITLE
Android requires min SDK 22?

### ISSUE THREAD

**Issue by FCView** [ponnamkarthik/FlutterToast#474]
Did we really need to increase the min SDK in 8.2.3? 

This is a breaking change and would force me to stop supporting 21.

**Comment by Weav3r** [comment]
Broke our app as well but it's been reverted with version 8.2.4

**Comment by nickesk** [comment]
See also #475

**Comment by FCView** [comment]
Fixed in [8.2.4](https://pub.dev/packages/fluttertoast/changelog#824) so I'm going to mark this closed.
