### ISSUE TITLE
Because app depends on fluttertoast ^2.1.0 which doesn't match any versions

### ISSUE THREAD

**Issue by needou** [PonnamKarthik/FlutterToast#5]
Because app depends on fluttertoast ^2.1.0 which doesn't match any versions，
Please Release version 2.0.1

**Comment by PonnamKarthik** [comment]
please check it now there is a an error in the Readme.md 


now i have updated plugin version to 2.0.4

` fluttertoast: ^2.0.4`

**Comment by needou** [comment]
@PonnamKarthik Thanks
