### ISSUE TITLE
Kindly add MacOs support and atelast not give errors in testinf for MAC OS also fix BUGS in issues

### ISSUE THREAD

**Issue by fisforfaheem** [ponnamkarthik/FlutterToast#503]
MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast),

**Comment by ponnamkarthik** [comment]
Hello @fisforfaheem,

Currenly for other os apart from android and ios we have to use toasts with context 

will work on the support without context

**Comment by fisforfaheem** [comment]
Any examples for.macos and web..

**Comment by ponnamkarthik** [comment]
Check this section of the docs

https://github.com/ponnamkarthik/FlutterToast?tab=readme-ov-file#toast-with-buildcontext-all-platforms
