### ISSUE TITLE
[WEB] Wasm support

### ISSUE THREAD

**Issue by rokk4** [ponnamkarthik/FlutterToast#511]
Do not hinder `wasm` compilation.
```
    Context: The unavailable library 'dart:html' is imported through these packages:
    
    web_plugin_registrant.dart => package:fluttertoast => dart:html
```

**Describe the solution you'd like**
Move away from `dart:html` and `dart:js`

> [package:web](https://pub.dev/packages/web), which replaces dart:html (and other web libraries)
> [dart:js_interop](https://api.dart.dev/stable/dart-js_interop), which replaces package:js and dart:js

https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm

**Comment by ponnamkarthik** [comment]
Please check latest version deployed few minutes back merged from PR #507
