### ISSUE TITLE
It's not a good idea to make incompatible API changes

### ISSUE THREAD

**Issue by SirLYC** [PonnamKarthik/FlutterToast#52]
Today after I ran pub get, I got some error. And I found out that this lib had changed static method to single instance. However, the major version is still 2. According to [semver.org](https://semver.org/), it's not recommended to change your api without a major version changed...

**Comment by PonnamKarthik** [comment]
Hello, @SirLYC Sorry for the inconvenience I will revert back it.

**Comment by a396901990** [comment]
same issue

**Comment by a396901990** [comment]
@PonnamKarthik r u going to revert back? Or can change my code to using instance.  
Thanks.

**Comment by PonnamKarthik** [comment]
@SirLYC @a396901990 reverted back to previous in version 2.2.8

I have added a feature to cancel the toasts
If you have a mac can you please test it and let me know

**Comment by a396901990** [comment]
@PonnamKarthik working well with 2.28

**Comment by PonnamKarthik** [comment]
@a396901990 Thanks for testing 
closing the issue as it it fixed :)
