### ISSUE TITLE
Having full issues with version 8.2.8

### ISSUE THREAD

**Issue by dev-deepakkumar** [ponnamkarthik/FlutterToast#532]
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt:9:48: warning: 'Registrar' is deprecated. Deprecated in Java
import io.flutter.plugin.common.PluginRegistry.Registrar
                                               ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:18:24: warning: 'FlutterMain' is deprecated. Deprecated in Java
import io.flutter.view.FlutterMain
                       ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:59:40: warning: 'setColorFilter(Int, PorterDuff.Mode): Unit' is deprecated. Deprecated in Java
                    gradientDrawable!!.setColorFilter(bgcolor.toInt(), PorterDuff.Mode.SRC_IN)
                                       ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:74:35: warning: 'FlutterMain' is deprecated. Deprecated in Java
                        val key = FlutterMain.getLookupKeyForAsset(fontAsset)
                                  ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:77:29: warning: 'setter for view: View?' is deprecated. Deprecated in Java
                    mToast?.view = layout
                            ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:81:58: warning: 'getter for view: View?' is deprecated. Deprecated in Java
                        val textView: TextView = mToast?.view!!.findViewById(android.R.id.message)
                                                         ^
C:\Users\ram\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.8\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:90:39: warning: 'FlutterMain' is deprecated. Deprecated in Java
                            val key = FlutterMain.getLookupKeyForAsset(fontAsset)
                                      ^

**Comment by WaseemAlqahwaji** [comment]
same issue not fixed

**Comment by SidanTechnologies** [comment]
Yaa It's been a month and still not fixed

**Comment by MarlonJD** [comment]
same issue here
