### ISSUE TITLE
lack ; in ios

### ISSUE THREAD

**Issue by reply-1988** [PonnamKarthik/FlutterToast#54]
![default](https://user-images.githubusercontent.com/30235918/51730223-9a355f00-20b1-11e9-9f8a-814a46ee42dd.png)

**Comment by reply-1988** [comment]
@PonnamKarthik  are you test this on ios platform?
My friends said in 2.2.8, they met many errors except this bug.
If you run this on Ios for a test, may find these errors.
Thank you.

**Comment by laptrinhcomvn** [comment]
Same here to me, i got many errors after upgrade:

`/Users/tung/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.9/ios/Classes/FluttertoastPlugin.m:87:16: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'id  _Nullable __strong' [-Wint-conversion]
result(true);
^~~~
In module 'UIKit' imported from /Volumes/WORK/PROJECTS/XXX/SRC/xxx_app/xxx_app/ios/Pods/Target Support Files/fluttertoast/fluttertoast-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/stdbool.h:32:14: note: expanded from macro 'true'
#define true 1
^
/Users/tung/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.9/ios/Classes/FluttertoastPlugin.m:48:19: warning: unused variable 'size' [-Wunused-variable]
NSNumber *size = call.arguments[@"size"];
^
4 warnings and 2 errors generated.
Could not build the application for the simulator.
`
