### ISSUE TITLE
Add support for textDirection (LTR and RTL) in Toast messages

### ISSUE THREAD

**Issue by mehmetakdumn604** [ponnamkarthik/FlutterToast#540]
Hello,

First of all, thank you for maintaining and developing this great library!

I am working on an app that requires support for both Left-to-Right (LTR) and Right-to-Left (RTL) text directions in toast messages, especially for languages like Arabic. Currently, there is no built-in support in the library to handle textDirection, which makes it difficult to properly display RTL languages.

It would be incredibly helpful if you could add an option to set the text direction (LTR/RTL) within the CSToastStyle or any other relevant part of the library. This would allow developers to easily toggle between these directions based on the language of the message.

Thank you for considering this feature request!

Best regards,
Mehmet AKDUMAN

**Comment by mohhamad-esmaili** [comment]
You can pass `TextDirection.rtl` in the child of showToast like:
```
fToast.showToast(
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 12.0),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
          color: Colors.greenAccent,
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.check),
            SizedBox(
              width: 12.0,
            ),
            Text(
              "This is a Custom Toast",
              textDirection: TextDirection.rtl, // here is direction
            ),
          ],
        ),
      ),
      gravity: ToastGravity.BOTTOM,
      toastDuration: Duration(seconds: 2),
    );
```
