### ISSUE TITLE
toast with app logo + text

### ISSUE THREAD

**Issue by dineshnaikb** [ponnamkarthik/FlutterToast#544]
![image](https://github.com/user-attachments/assets/dba8268d-3079-4db2-8a20-1183ac3c5e2f)
[doc link](https://developer.android.com/guide/topics/ui/notifiers/toasts)

**Comment by ponnamkarthik** [comment]
If your app targets Android 12 (API level 31) or higher, its toast is limited to two lines of text and shows the application icon next to the text. Be aware that the line length of this text varies by screen size, so it's good to make the text as short as possible.

Its controlled by the android system plugin has no control over that

if you use [toast with context ](https://github.com/ponnamkarthik/FlutterToast?tab=readme-ov-file#toast-with-buildcontext-all-platforms) then you can customise the look of the toast

**Comment by dineshnaikb** [comment]
![image](https://github.com/user-attachments/assets/07da7b31-23c3-4383-bd01-71dace3588bb)
@ponnamkarthik

**Comment by dineshnaikb** [comment]
@ponnamkarthik 8.2.2 working fine can u check that code and compare with latest

**Comment by dineshnaikb** [comment]
![image](https://github.com/user-attachments/assets/a2d17eb1-d5c1-4364-8cf9-416101104a35)
same issue, new version
if us 8.2.2 version
![image](https://github.com/user-attachments/assets/b0dab131-5adf-4dd9-8626-6f79ee611603)
```import 'package:fluttertoast/fluttertoast.dart';

void flutterToast(String message) {
  Fluttertoast.showToast(
    msg: message.toCapitalize(),
    toastLength: Toast.LENGTH_SHORT,
    gravity: ToastGravity.BOTTOM,
    backgroundColor: ColorResources.gray,
    textColor: ColorResources.textWhite,
    fontSize: 14.0,
  );
}
```
