### ISSUE TITLE
Compatibility Issue: fluttertoast: 8.2.8 with Latest Flutter SDK

### ISSUE THREAD

**Issue by HananMustafa** [ponnamkarthik/FlutterToast#545]
The latest version of fluttertoast (8.2.8) throws compilation errors due to the usage of deprecated APIs like PluginRegistry.Registrar and FlutterMain, which are incompatible with the latest Flutter SDK using Android embedding v2.

Error Details:
Unresolved reference: Registrar
Unresolved reference: FlutterMain

Steps to reproduce:
Upgrade Flutter to the latest version (3.27.0)
Add fluttertoast: 8.2.8 to the project.
Build the project.

**Comment by alfayej55** [comment]
I have read same problem. After updating the flutter sdk , it is not working for me either

**Comment by jahid012** [comment]
I also got that problem in my existing project. Is there any fix, please?

**Comment by a-babayev** [comment]
Same problem here

**Comment by SangWook16074** [comment]
I also experienced the same error.

In my case, I updated the version of Flutter, and that version was not a stable version.

**Comment by SangWook16074** [comment]
Run below command

**Comment by a-babayev** [comment]
> I also experienced the same error.
> 
> In my case, I updated the version of Flutter, and that version was not a stable version.
> 
> Flutter's stable version is 3.24. And Flutter recommend use stable version.
> 
> Run below command
> 
> `flutter channel stable` `flutter pub cache repair` `flutter pub get`
> 
> finally, I solved this problem.

But the issue relates to latest version (3.27.0) @SangWook16074

**Comment by SangWook16074** [comment]
> > I also experienced the same error.
> 
> > 
> 
> > In my case, I updated the version of Flutter, and that version was not a stable version.
> 
> > 
> 
> > Flutter's stable version is 3.24. And Flutter recommend use stable version.
> 
> > 
> 
> > Run below command
> 
> > 
> 
> > `flutter channel stable` `flutter pub cache repair` `flutter pub get`
> 
> > 
> 
> > finally, I solved this problem.
> 
> 
> 
> But the issue relates to latest version (3.27.0) @SangWook16074 

@a-babayev 

you're right. 

However, 3.27.0 is currently in beta. Maybe version 3.27.0 is not compatible with fluttertoast 8.2.8

I think we will have to use the stable version 3.24 for now.

**Comment by arc0489** [comment]
Same problem here. Flutter 3.27+ has 3 warnings.. Unresolved reference: Registrar, FlutterMain, FlutterMain

**Comment by sunilsinghchaudhary00** [comment]
> This was already fixed in [#543](https://github.com/ponnamkarthik/FlutterToast/pull/543) but it is not yet published in pub.dev so you can use this in the meantime
> 
> ```
> fluttertoast:
>     git:
>       url: git@github.com:ponnamkarthik/FlutterToast.git
> ```

stderr: Cloning into bare repository 'C:\Users\addd\AppData\Local\Pub\Cache\_temp\dirc84f2590'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
