### ISSUE TITLE
Command `flutter build ios` failed with error when running in example folder

### ISSUE THREAD

**Issue by showgp** [PonnamKarthik/FlutterToast#55]
When running `flutter build ios` in example folder, the following errors occur:

```sh
FluttertoastPlugin.m:87:16: error: implicit conversion of 'int' to 'id _Nullable' is disallowed with ARC
            result(true);
                   ^~~~

FluttertoastPlugin.m:41:16: error: implicit conversion of 'int' to 'id _Nullable' is disallowed with ARC
            result(true);
                   ^~~~
```

FlutterToast version: 2.2.9

Xcode version: 10.1

Flutter version: 1.1.9

**Comment by showgp** [comment]
Maybe replace `result(true)` with `result([NSNumber numberWithBool:true])` could solve this problem?

**Comment by lane128** [comment]
I also had the same issue. In ARC mode, build print
 ```Implicit conversion of 'int' to 'id _Nullable' is disallowed with ARC``` 
as @showgp  mentioned, modify ```result(true)``` with ```result([NSNumber numberWithBool:true])``` would fix it.
