### ISSUE TITLE
Toast backgroung issue

### ISSUE THREAD

**Issue by vaderot** [PonnamKarthik/FlutterToast#58]
Some additional background when add line "background Color: Colors.black12"

Fluttertoast.showToast(
        msg: "loginSuccess",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.BOTTOM,
        timeInSecForIos: 1,
        backgroundColor: Colors.black12,
        textColor: Colors.black54,
        fontSize: 16.0
    );
![photo_2019-01-30_12-08-02](https://user-images.githubusercontent.com/10448837/51974114-dbe65100-2487-11e9-9228-a9f247f97a7e.jpg)

**Comment by GeekTR** [comment]
I had the same problem.

**Comment by Stephan-Enoro** [comment]
Same here. Android 9 device

**Comment by ben-hunter-hansen** [comment]
Same issue here as well.

**Comment by kyungjoongo** [comment]
same

**Comment by w4ll3** [comment]
Same here on my Android 9 device, any news?

**Comment by marcuslma** [comment]
Same here

**Comment by PonnamKarthik** [comment]
check v3.0.4
