### ISSUE TITLE
Build error iOS v.2.0.4

### ISSUE THREAD

**Issue by KosrenDQ** [PonnamKarthik/FlutterToast#6]
1. Flutter doctor says everything is fine :D

If i try to build my app with flutter toast on iOS i get the following error message:
no visible @interface for 'FluttertoastPlugin' declares the selector 'intFromHexString:'
      unsigned int hexint = [self intFromHexString:hexStr];

Any idea?
I already updated all pods and librarys.

**Comment by zxj5470** [comment]
The same to me....
Xcode's output:
           ↳
[        ] === BUILD TARGET fluttertoast OF PROJECT Pods WITH CONFIGURATION Debug ===
           In file included from /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:1:
           In file included from /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.h:1:
           In file included from /Volumes/OS_X_Files/git/whitewoodcity/social-vertx-flutter/flutter_app/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:37:
           In file included from /Volumes/OS_X_Files/git/whitewoodcity/social-vertx-flutter/flutter_app/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
           /Volumes/OS_X_Files/git/whitewoodcity/social-vertx-flutter/flutter_app/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:140:58: warning: this block declaration is not a prototype [-Wstrict-prototypes]
                                 completionHandler:(nonnull void (^)())completionHandler;
                                                                    ^
                                                                     void
           /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:60:43: warning: 'call' used as the name of the previous parameter rather than as part of the selector [-Wmissing-selector-name]
           - (void)showToastView:(FlutterMethodCall*)call:(NSString*)msg {
                                                     ^
           /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:60:43: note: introduce a parameter name to make 'call' part of the selector
           /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:60:47: note: or insert whitespace before ':' to use 'call' as parameter name and have an empty entry in the selector
           - (void)showToastView:(FlutterMethodCall*)call:(NSString*)msg {
                                                         ^
           /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:16:23: warning: unused variable 'viewController' [-Wunused-variable]
               UIViewController *viewController =
                                 ^
           /Volumes/OS_X_Files/ideaProjects/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.0.4/ios/Classes/FluttertoastPlugin.m:67:31: error: no visible @interface for 'FluttertoastPlugin' declares the selector 'intFromHexString:'
             unsigned int hexint = [self intFromHexString:hexStr];
                                    ~~~~ ^~~~~~~~~~~~~~~~
           3 warnings and 1 error generated.

**Comment by PonnamKarthik** [comment]
Package Updated 

`fluttertoast: ^2.0.6`
