### ISSUE TITLE
version 3.0.0 AndroidX release fail

### ISSUE THREAD

**Issue by LatinaIsaac** [PonnamKarthik/FlutterToast#65]
`  -R\
          C:\Users\x\Desktop\cvcro\build\fluttertoast\intermediates\res\compiled\release\drawable-mdpi-v4_abc_btn_radio_to_on_mtrl_000.png.flat\
          -R\
          C:\Users\x\Desktop\cvcro\build\fluttertoast\intermediates\res\compiled\release\drawable-mdpi-v4_abc_btn_radio_to_on_mtrl_015.png.flat\
          C:\Users\jx\Desktop\cvcro\build\fluttertoast\intermediates\res\compiled\release\values_values.arsc.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s`

**Comment by sabari1004** [comment]
I am facing the same issue

**Comment by xyzbilal** [comment]
any solution will be provided ?

**Comment by binyan-x** [comment]
edit  build.gradle

compileSdkVersion 28  
targetSdkVersion 28

修改build.gradle  将版本改为28可解决

**Comment by xyzbilal** [comment]
> edit build.gradle
> 
> compileSdkVersion 28
> targetSdkVersion 28
> 
> 修改build.gradle 将版本改为28可解决

it doesnt work.  same error.

**Comment by dpjanes** [comment]
Seeing similar issues here.

**Comment by PonnamKarthik** [comment]
check with `3.0.1` version

**Comment by lizhuoyuan** [comment]
3.0.1 failed

**Comment by PonnamKarthik** [comment]
try 
`flutter clean`
and then 
`flutter build apk --release`

**Comment by LatinaIsaac** [comment]
> try
`flutter clean`
and then
`flutter build apk --release`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Android dependency 'androidx.appcompat:appcompat' has different version for the compile (1.0.0-rc01) and runtime (1.1.0-alpha02) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      55,2s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by lhcdims** [comment]
3.0.0 OK, 3.0.1 failed, just rolled back to 3.0.0
Testing by Mobile Phone: Mi Max, Android Verion 7.0 (API 24)

**Comment by PonnamKarthik** [comment]
@LatinaIsaac try this one

```gradle
android {
    configurations.all {
        resolutionStrategy.force 'androidx.appcompat:appcompat:1.0.0-rc01'
    }
}
```

or update your androidx appcompat version the `1.1.0-alpha02`

**Comment by LatinaIsaac** [comment]
thx all.

fixed with the default gradle dependencies https://github.com/PonnamKarthik/FlutterToast/blob/master/example/android/app/build.gradle

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.2-alpha01'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.2-alpha01'
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha02'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
