### ISSUE TITLE
Toast is hidden behind the notch on iPhone XR

### ISSUE THREAD

**Issue by grandpa-guru** [PonnamKarthik/FlutterToast#66]
![image](https://user-images.githubusercontent.com/12012869/52936204-ca43eb00-335b-11e9-9157-584a917f7e09.png)

Toast is hidden behind the notch on iPhone XR if its position is set to TOP and **when using SafeArea**.

**Comment by krsolutions** [comment]
Same here

**Comment by ueabu** [comment]
Yeah, same issue here.

**Comment by Ptanium** [comment]
Same problem on IOS Emulator.Anyone same problem on real device?

**Comment by PonnamKarthik** [comment]
hope its fixed in `3.0.5` Please check and let me know

**Comment by Ptanium** [comment]
Fixed
3.1.0 is working
