### ISSUE TITLE
Latest versions failed to install

### ISSUE THREAD

**Issue by hemandroid** [PonnamKarthik/FlutterToast#71]
I tried with your latest version fluttertoast: ^3.0.1 It causing build failed and displaying due to AndroidX and when I'm trying to migrating the project to AndroidX. It doesn't show anything to migrate.

For version to support below AndroidX using fluttertoast version 2.2.12 It is also a big error, as 2.2.12 is not exists. So, I'm using 2.2.2, which is working fine. So please look into this issue and do the needful asap.

**Comment by gqfjob** [comment]
so do I

**Comment by PonnamKarthik** [comment]
check with v3.0.2
