### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'

### ISSUE THREAD

**Issue by robindijkhof** [PonnamKarthik/FlutterToast#73]
I got the following error on 3.0.1

flutter Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: Program type already present: com.google.common.util.concurrent.ListenableFuture

3.0.0 workes fine though

**Comment by PonnamKarthik** [comment]
can you check your android gradle file whether your compile SDK version is 28 or not

**Comment by robindijkhof** [comment]
Compilesdk 28, targetsdk 27
