### ISSUE TITLE
App crashes and note that it uses or overrides a deprecated API

### ISSUE THREAD

**Issue by evont** [PonnamKarthik/FlutterToast#78]
Flutter version: v1.3.10-pre.4
fluttertoast version: ^3.0.3

I got a note below:

/Users/evont/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.0.3/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java uses or overrides a deprecated API

**Comment by kkaun** [comment]
Same issue here. Migrating to AndroidX doesn't actually help.

**Comment by evont** [comment]
Use the stable channel can fix it, but i don't know why.

**Comment by devbijoy274** [comment]
Same issue here. Any reference, which version would work for me fine, using Flutter v1.2

**Comment by manish4353** [comment]
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.xxx.xxxxx signatures do not match the previously installed version; ignoring!]

**Comment by manish4353** [comment]
Note: C:\Users\pc\AppData\Local\Android\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.0.3\android\src\main\java\io\github\ponnamkarthik\toast\fluttertoast\FluttertoastPlugin.java uses or overrides a deprecated API.

**Comment by PonnamKarthik** [comment]
fixed in `v3.0.5`
