### ISSUE TITLE
Cannot build in Xcode throws ARC semantic issue

### ISSUE THREAD

**Issue by vijaykanta** [PonnamKarthik/FlutterToast#8]
I was trying to do last time building before I create a release. It was all ok during debugging. But today I created new developer certificate with agent for provision, changed the bundle ID to match my App Store bundle id, then tried 'flutter run' or Xcode 'Runner', both throw the following issue.

`No visible  @interface for 'FlutterToastPlugin' declares the selector 'intFromHexString:' FlutterToastPlugin.m`

Also in Xcode the file opens giving red highlight to line #67

**Comment by fisherdan** [comment]
I encounter the same issue, any solutions for it?

**Comment by PonnamKarthik** [comment]
Package update 

`fluttertoast: ^2.0.6`
