### ISSUE TITLE
java.lang.Exception: denglibo Toast callstack! strTip=This is Short Toast

### ISSUE THREAD

**Issue by huluxia** [PonnamKarthik/FlutterToast#81]
java.lang.Exception: denglibo Toast callstack! strTip=This is Short Toast

**Comment by huluxia** [comment]
FloatingActionButton

**Comment by 982991084** [comment]
同求，怎么解决啊

**Comment by lifetin** [comment]
和我一样啊
https://github.com/PonnamKarthik/FlutterToast/issues/87
