### ISSUE TITLE
toast message still appear even if app on background or closed

### ISSUE THREAD

**Issue by kw2019ltd** [PonnamKarthik/FlutterToast#84]
![Screenshot_20190401-181439](https://user-images.githubusercontent.com/47334522/55343237-5d238980-54b3-11e9-855c-de6110626cb0.jpg)

**Comment by kw2019ltd** [comment]
void showToast(var msg, BuildContext context) {
  Fluttertoast.showToast(
      msg: msg,
      gravity: ToastGravity.BOTTOM,
      toastLength: Toast.LENGTH_SHORT,
      backgroundColor: Theme.of(context).primaryColor,
      textColor: Theme.of(context).indicatorColor);
}

**Comment by PonnamKarthik** [comment]
@kw2019ltd  Toast messages default function is this it will show even the app is background.
