### ISSUE TITLE
FluttertoastPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by kw2019ltd** [PonnamKarthik/FlutterToast#85]
Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.0.3/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by pmrajani** [comment]
I have same issue. How can i resolve it?

**Comment by rmzntimur** [comment]
I have same problem. what can i do?

**Comment by manish4353** [comment]
Same issue with me too.

**Comment by BlueskyFR** [comment]
Same here.

**Comment by samuelg123** [comment]
Same issue.
``` 
Note: C:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.0.4\android\src\main\java\io\github\ponnamkarthik\toast\fluttertoast\FluttertoastPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by fahjan** [comment]
same note with fluttertoast-3.0.4

**Comment by c0h1b4** [comment]
Same here

**Comment by Xgamefactory** [comment]
same...
`\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.0.4\android\src\main\java\io\github\ponnamkarthik\toast\fluttertoast\FluttertoastPlugin.java uses or overrides a deprecated API.`

**Comment by yourvijay** [comment]
same here
.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.0.4/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java

**Comment by PonnamKarthik** [comment]
fixed in `v3.0.5`

**Comment by cahyowhy** [comment]
i get this issue on v3.1.2

**Comment by bestkanthed** [comment]
i get this issue on v3.1.2
