### ISSUE TITLE
报错了.显示内容

### ISSUE THREAD

**Issue by lifetin** [ponnamkarthik/FlutterToast#87]
报错了.显示内容

![44](https://user-images.githubusercontent.com/10474968/55981701-e1eb8000-5cc9-11e9-9e8f-1db499f34db3.png)

**Comment by PonnamKarthik** [comment]
@lifetin I was unable to replicate the issue

**Comment by 982991084** [comment]
W/System.err( 5318): java.lang.Exception: denglibo Toast callstack! strTip=
W/System.err( 5318):    at android.widget.Toast.show(Toast.java:127)
W/System.err( 5318):    at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:116)
W/System.err( 5318):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err( 5318):    at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
W/System.err( 5318):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
W/System.err( 5318):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 5318):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 5318):    at android.os.Looper.loop(Looper.java:122)
W/System.err( 5318):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 5318):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5318):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5318):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err( 5318):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
W/System.err( 5318): java.lang.Exception: denglibo Toast callstack! strTip=
W/System.err( 5318):    at android.widget.Toast.show(Toast.java:127)
W/System.err( 5318):    at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:116)
W/System.err( 5318):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err( 5318):    at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
W/System.err( 5318):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
W/System.err( 5318):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 5318):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 5318):    at android.os.Looper.loop(Looper.java:122)
W/System.err( 5318):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 5318):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5318):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5318):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err( 5318):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

一样报错，但可以用

**Comment by PonnamKarthik** [comment]
@982991084 unable to replicate the issue

**Comment by kuaifengle** [comment]
me too     version:  fluttertoast: ^3.1.0

**Comment by lifetin** [comment]
![11](https://user-images.githubusercontent.com/10474968/59175889-c7c70480-8b89-11e9-98b6-3479aa79127d.png)

升级到
 fluttertoast: ^3.1.0
还是一样的问题!!!

**Comment by twovs** [comment]
I was catch this error ,what can I do ?

**Comment by orchie** [comment]
when i try to toast then get error.
## my pubspec
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.13
  shared_preferences: ^0.5.3+4
  json_serializable: ^3.1.0
  fluttertoast: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.4
```
## my env
win10 64,
Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (3 weeks ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0
## the err show.
```
E/flutter (14110): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter (14110): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (14110): <asynchronous suspension>
E/flutter (14110): #1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:77:31)
E/flutter (14110): <asynchronous suspension>
E/flutter (14110): #2      _LoginState.build.<anonymous closure> (package:myapp/page/login.dart:184:40)
E/flutter (14110): <asynchronous suspension>
E/flutter (14110): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (14110): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (14110): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14110): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (14110): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (14110): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (14110): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (14110): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14110): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14110): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14110): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14110): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (14110): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14110): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (14110): #17     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (14110): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (14110):
```
# amazing...i upgrade flutter to newest,then it works,but also console error.
it shows in app.now my flutter is *Flutter 1.7.8+hotfix.4*
error code
```
W/System.err(14566): java.lang.Exception: denglibo Toast callstack! strTip=
W/System.err(14566):    at android.widget.Toast.show(Toast.java:127)
W/System.err(14566):    at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:114)
W/System.err(14566):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(14566):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(14566):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
W/System.err(14566):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(14566):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err(14566):    at android.os.Looper.loop(Looper.java:122)
W/System.err(14566):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err(14566):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14566):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(14566):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err(14566):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/EGL_adreno(14566): tid 14593: eglSurfaceAttrib(1319): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer(14566): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa053f6c0, error=EGL_BAD_MATCH
D/EGL_adreno(14566): eglMakeCurrent: 0xb3ef7e80: ver 3 1 (tinfo 0xa2312420)
D/EGL_adreno(14566): eglMakeCurrent: 0xb3ef7e80: ver 3 1 (tinfo 0xa2312420)
```
## thanks for your toast~ @PonnamKarthik

**Comment by pjqdyd** [comment]
**I get the same error, But it works.**

**Comment by leyan95** [comment]
### v3.0.1 still reports this error, but it is available.

![image](https://user-images.githubusercontent.com/35946000/73904636-9c8ee380-48d7-11ea-9dd3-d40868bc9bd6.png)
