### ISSUE TITLE
can I control toast disappear time ?

### ISSUE THREAD

**Issue by YDJSZY** [PonnamKarthik/FlutterToast#90]
Now,it show time too short

**Comment by kennenfromchina** [comment]
On iOS, there is a toast framework that automatically determines the time of disappearance based on message length

**Comment by kennenfromchina** [comment]
`+ (NSTimeInterval)displayDurationForString:(NSString*)string {
    CGFloat minimum = MAX((CGFloat)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);
    return MIN(minimum, [self sharedView].maximumDismissTimeInterval);
}
``objective-c

**Comment by kennenfromchina** [comment]
```objective-c
+ (NSTimeInterval)displayDurationForString:(NSString*)string {
    CGFloat minimum = MAX((CGFloat)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);
    return MIN(minimum, [self sharedView].maximumDismissTimeInterval);
}
```

**Comment by PonnamKarthik** [comment]
for ios `timeInSecForIos` and for androifd `toastLength`
