### ISSUE TITLE
Flutter 1.5/release/ios or android/do not work/no logs/works in debug

### ISSUE THREAD

**Issue by liguande** [PonnamKarthik/FlutterToast#91]

**Comment by li-xiaojun** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast
```

**Comment by PonnamKarthik** [comment]
@liguande @li-xiaojun I have tested it with example code its working fine

```
Flutter 1.5.4-hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (2 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

can you please provide a code sample with error

**Comment by PonnamKarthik** [comment]
I have updated the code `3.0.5` please check it with this version

**Comment by liguande** [comment]
fluttertoast-3.0.5/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:7: Error: android.support.v4.content.res Does not Exist
import android.support.v4.content.res.ResourcesCompat;

**Comment by liguande** [comment]
Oh I'm sorry.Maybe because I changed the ndk, my other project is working well.
