### ISSUE TITLE
fluttertoast: ^3.0.6   cannot find symbol 

### ISSUE THREAD

**Issue by pmrajani** [PonnamKarthik/FlutterToast#93]
cannot find symbol shapeDrawable = ResourcesCompat.getDrawable(ctx.getResources(), R.drawable.toast_bg, null);

![Screenshot_1](https://user-images.githubusercontent.com/4957175/57831543-0e1b8480-77d3-11e9-8f4b-fa157aad97b7.png)
@PonnamKarthik

**Comment by qq1057119720** [comment]
Yes, adnroidx support is covered

**Comment by pmrajani** [comment]
what will be solution? I am using AndroidX

**Comment by qq1057119720** [comment]
I don't know, plugins making local paths is one way.

**Comment by PonnamKarthik** [comment]
check with new version `3.1.0`

**Comment by qq1057119720** [comment]
ok,thanks
