### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

### ISSUE THREAD

**Issue by Yxliam** [ponnamkarthik/FlutterToast#97]
Hello, I reported an error when using this library.
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

**Comment by jicg** [comment]
me too

**Comment by Huyamin150** [comment]
did you solve it? @Yxliam

**Comment by Yxliam** [comment]
@Huyamin150 Version back to 3.0.3 fluttertoast: "<=3.0.3"

**Comment by luofeng0603** [comment]
I got the same error .
Even I backed the fluttertoast version to 3.0.3 still got the same error.
My flutter version is 1.8.2

**Comment by Mephistol** [comment]
I got the same error .
I use the fluttertoast version 2.2.11 still got the same error.
Specially, I use it in a Mixed App (Add flutter into an existing Android app)

**Comment by cxmmxc** [comment]
the same too

**Comment by cxmmxc** [comment]
> the same too

flutter clean, and restart, then it ok

**Comment by xhp281** [comment]
> > the same too
> 
> flutter clean, and restart, then it ok

mee to

**Comment by HongxiangShe** [comment]
> Hello, I reported an error when using this library.
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

maybe you should call this GeneratedPluginRegistrant.register(with: self)

**Comment by chenxin04187** [comment]
i also got the same error
![image](https://user-images.githubusercontent.com/30694362/72258757-ce4eba80-3649-11ea-90fa-6b3f27761112.png)

and i also tried to run flutter clean,and rerun the application,but it all doesn't work!

my situation is as follows:
![image](https://user-images.githubusercontent.com/30694362/72258936-44532180-364a-11ea-87cb-5efbdc3aeea3.png)
![image](https://user-images.githubusercontent.com/30694362/72258950-4b7a2f80-364a-11ea-952d-9dc8b641f06a.png)

**Comment by JohnnyLuv** [comment]
if u installed just now
reload the object can resolve it

**Comment by fajusto** [comment]
I’ve just solved this problem by stop completely and run again.

**Comment by MustafaAdam** [comment]
What worked for me is a `flutter clean` and a complete stop.
When restarted, it worked.

I'm not saying this will solve it for you, but it did for me, so try it.
